// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: order_service.proto

package orderservicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderServiceGRPC_GetAllInvoices_FullMethodName = "/orderservice.OrderServiceGRPC/GetAllInvoices"
)

// OrderServiceGRPCClient is the client API for OrderServiceGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceGRPCClient interface {
	GetAllInvoices(ctx context.Context, in *GetAllInvoicesRequest, opts ...grpc.CallOption) (*GetAllInvoicesResponse, error)
}

type orderServiceGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceGRPCClient(cc grpc.ClientConnInterface) OrderServiceGRPCClient {
	return &orderServiceGRPCClient{cc}
}

func (c *orderServiceGRPCClient) GetAllInvoices(ctx context.Context, in *GetAllInvoicesRequest, opts ...grpc.CallOption) (*GetAllInvoicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllInvoicesResponse)
	err := c.cc.Invoke(ctx, OrderServiceGRPC_GetAllInvoices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceGRPCServer is the server API for OrderServiceGRPC service.
// All implementations must embed UnimplementedOrderServiceGRPCServer
// for forward compatibility.
type OrderServiceGRPCServer interface {
	GetAllInvoices(context.Context, *GetAllInvoicesRequest) (*GetAllInvoicesResponse, error)
	mustEmbedUnimplementedOrderServiceGRPCServer()
}

// UnimplementedOrderServiceGRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceGRPCServer struct{}

func (UnimplementedOrderServiceGRPCServer) GetAllInvoices(context.Context, *GetAllInvoicesRequest) (*GetAllInvoicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllInvoices not implemented")
}
func (UnimplementedOrderServiceGRPCServer) mustEmbedUnimplementedOrderServiceGRPCServer() {}
func (UnimplementedOrderServiceGRPCServer) testEmbeddedByValue()                          {}

// UnsafeOrderServiceGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceGRPCServer will
// result in compilation errors.
type UnsafeOrderServiceGRPCServer interface {
	mustEmbedUnimplementedOrderServiceGRPCServer()
}

func RegisterOrderServiceGRPCServer(s grpc.ServiceRegistrar, srv OrderServiceGRPCServer) {
	// If the following call pancis, it indicates UnimplementedOrderServiceGRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderServiceGRPC_ServiceDesc, srv)
}

func _OrderServiceGRPC_GetAllInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllInvoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceGRPCServer).GetAllInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderServiceGRPC_GetAllInvoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceGRPCServer).GetAllInvoices(ctx, req.(*GetAllInvoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderServiceGRPC_ServiceDesc is the grpc.ServiceDesc for OrderServiceGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderServiceGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderservice.OrderServiceGRPC",
	HandlerType: (*OrderServiceGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllInvoices",
			Handler:    _OrderServiceGRPC_GetAllInvoices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_service.proto",
}
