// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: elasticsearch_service.proto

package elasticsearchservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	RoleName      string                 `protobuf:"bytes,8,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	CreatedAtGte  string                 `protobuf:"bytes,9,opt,name=created_at_gte,json=createdAtGte,proto3" json:"created_at_gte,omitempty"`
	CreatedAtLte  string                 `protobuf:"bytes,10,opt,name=created_at_lte,json=createdAtLte,proto3" json:"created_at_lte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_elasticsearch_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elasticsearch_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_elasticsearch_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUsersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUsersRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetUsersRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *GetUsersRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUsersRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUsersRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetUsersRequest) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *GetUsersRequest) GetCreatedAtGte() string {
	if x != nil {
		return x.CreatedAtGte
	}
	return ""
}

func (x *GetUsersRequest) GetCreatedAtLte() string {
	if x != nil {
		return x.CreatedAtLte
	}
	return ""
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_elasticsearch_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elasticsearch_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_elasticsearch_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	RoleName      string                 `protobuf:"bytes,6,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_elasticsearch_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_elasticsearch_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_elasticsearch_service_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *User) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetProductsRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Offset                int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                 int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy                string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	CategoryId            string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	BrandId               string                 `protobuf:"bytes,5,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Name                  string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description           string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Sex                   string                 `protobuf:"bytes,8,opt,name=sex,proto3" json:"sex,omitempty"`
	PriceGte              string                 `protobuf:"bytes,9,opt,name=price_gte,json=priceGte,proto3" json:"price_gte,omitempty"`
	PriceLte              string                 `protobuf:"bytes,10,opt,name=price_lte,json=priceLte,proto3" json:"price_lte,omitempty"`
	DiscountPercentageGte string                 `protobuf:"bytes,11,opt,name=discount_percentage_gte,json=discountPercentageGte,proto3" json:"discount_percentage_gte,omitempty"`
	DiscountPercentageLte string                 `protobuf:"bytes,12,opt,name=discount_percentage_lte,json=discountPercentageLte,proto3" json:"discount_percentage_lte,omitempty"`
	StockGte              string                 `protobuf:"bytes,13,opt,name=stock_gte,json=stockGte,proto3" json:"stock_gte,omitempty"`
	StockLte              string                 `protobuf:"bytes,14,opt,name=stock_lte,json=stockLte,proto3" json:"stock_lte,omitempty"`
	CategoryName          string                 `protobuf:"bytes,15,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	BrandName             string                 `protobuf:"bytes,16,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	CreatedAtGte          string                 `protobuf:"bytes,17,opt,name=created_at_gte,json=createdAtGte,proto3" json:"created_at_gte,omitempty"`
	CreatedAtLte          string                 `protobuf:"bytes,18,opt,name=created_at_lte,json=createdAtLte,proto3" json:"created_at_lte,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_elasticsearch_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elasticsearch_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_elasticsearch_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetProductsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetProductsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *GetProductsRequest) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *GetProductsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetProductsRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetProductsRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *GetProductsRequest) GetPriceGte() string {
	if x != nil {
		return x.PriceGte
	}
	return ""
}

func (x *GetProductsRequest) GetPriceLte() string {
	if x != nil {
		return x.PriceLte
	}
	return ""
}

func (x *GetProductsRequest) GetDiscountPercentageGte() string {
	if x != nil {
		return x.DiscountPercentageGte
	}
	return ""
}

func (x *GetProductsRequest) GetDiscountPercentageLte() string {
	if x != nil {
		return x.DiscountPercentageLte
	}
	return ""
}

func (x *GetProductsRequest) GetStockGte() string {
	if x != nil {
		return x.StockGte
	}
	return ""
}

func (x *GetProductsRequest) GetStockLte() string {
	if x != nil {
		return x.StockLte
	}
	return ""
}

func (x *GetProductsRequest) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *GetProductsRequest) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *GetProductsRequest) GetCreatedAtGte() string {
	if x != nil {
		return x.CreatedAtGte
	}
	return ""
}

func (x *GetProductsRequest) GetCreatedAtLte() string {
	if x != nil {
		return x.CreatedAtLte
	}
	return ""
}

type GetProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsResponse) Reset() {
	*x = GetProductsResponse{}
	mi := &file_elasticsearch_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResponse) ProtoMessage() {}

func (x *GetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elasticsearch_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return file_elasticsearch_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Sex                string                 `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Price              int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPercentage int32                  `protobuf:"varint,6,opt,name=discount_percentage,json=discountPercentage,proto3" json:"discount_percentage,omitempty"`
	Stock              int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	ImageUrl           string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CategoryId         string                 `protobuf:"bytes,9,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName       string                 `protobuf:"bytes,10,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	BrandId            string                 `protobuf:"bytes,11,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	BrandName          string                 `protobuf:"bytes,12,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_elasticsearch_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_elasticsearch_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_elasticsearch_service_proto_rawDescGZIP(), []int{5}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetDiscountPercentage() int32 {
	if x != nil {
		return x.DiscountPercentage
	}
	return 0
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Product) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Product) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Product) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *Product) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetInvoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAtGte  string                 `protobuf:"bytes,7,opt,name=created_at_gte,json=createdAtGte,proto3" json:"created_at_gte,omitempty"`
	CreatedAtLte  string                 `protobuf:"bytes,8,opt,name=created_at_lte,json=createdAtLte,proto3" json:"created_at_lte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoicesRequest) Reset() {
	*x = GetInvoicesRequest{}
	mi := &file_elasticsearch_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoicesRequest) ProtoMessage() {}

func (x *GetInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_elasticsearch_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoicesRequest.ProtoReflect.Descriptor instead.
func (*GetInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_elasticsearch_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetInvoicesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetInvoicesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetInvoicesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetInvoicesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetInvoicesRequest) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *GetInvoicesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetInvoicesRequest) GetCreatedAtGte() string {
	if x != nil {
		return x.CreatedAtGte
	}
	return ""
}

func (x *GetInvoicesRequest) GetCreatedAtLte() string {
	if x != nil {
		return x.CreatedAtLte
	}
	return ""
}

type GetInvoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoicesResponse) Reset() {
	*x = GetInvoicesResponse{}
	mi := &file_elasticsearch_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoicesResponse) ProtoMessage() {}

func (x *GetInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_elasticsearch_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoicesResponse.ProtoReflect.Descriptor instead.
func (*GetInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_elasticsearch_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_elasticsearch_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_elasticsearch_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_elasticsearch_service_proto_rawDescGZIP(), []int{8}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Invoice) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Invoice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Invoice) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Invoice) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_elasticsearch_service_proto protoreflect.FileDescriptor

const file_elasticsearch_service_proto_rawDesc = "" +
	"\n" +
	"\x1belasticsearch_service.proto\x12\x16elasticsearchservicepb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x02\n" +
	"\x0fGetUsersRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x1b\n" +
	"\trole_name\x18\b \x01(\tR\broleName\x12$\n" +
	"\x0ecreated_at_gte\x18\t \x01(\tR\fcreatedAtGte\x12$\n" +
	"\x0ecreated_at_lte\x18\n" +
	" \x01(\tR\fcreatedAtLte\"F\n" +
	"\x10GetUsersResponse\x122\n" +
	"\x05users\x18\x01 \x03(\v2\x1c.elasticsearchservicepb.UserR\x05users\"\x92\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x1b\n" +
	"\trole_name\x18\x06 \x01(\tR\broleName\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xd3\x04\n" +
	"\x12GetProductsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12\x19\n" +
	"\bbrand_id\x18\x05 \x01(\tR\abrandId\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x10\n" +
	"\x03sex\x18\b \x01(\tR\x03sex\x12\x1b\n" +
	"\tprice_gte\x18\t \x01(\tR\bpriceGte\x12\x1b\n" +
	"\tprice_lte\x18\n" +
	" \x01(\tR\bpriceLte\x126\n" +
	"\x17discount_percentage_gte\x18\v \x01(\tR\x15discountPercentageGte\x126\n" +
	"\x17discount_percentage_lte\x18\f \x01(\tR\x15discountPercentageLte\x12\x1b\n" +
	"\tstock_gte\x18\r \x01(\tR\bstockGte\x12\x1b\n" +
	"\tstock_lte\x18\x0e \x01(\tR\bstockLte\x12#\n" +
	"\rcategory_name\x18\x0f \x01(\tR\fcategoryName\x12\x1d\n" +
	"\n" +
	"brand_name\x18\x10 \x01(\tR\tbrandName\x12$\n" +
	"\x0ecreated_at_gte\x18\x11 \x01(\tR\fcreatedAtGte\x12$\n" +
	"\x0ecreated_at_lte\x18\x12 \x01(\tR\fcreatedAtLte\"R\n" +
	"\x13GetProductsResponse\x12;\n" +
	"\bproducts\x18\x01 \x03(\v2\x1f.elasticsearchservicepb.ProductR\bproducts\"\xd1\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\tR\x03sex\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12/\n" +
	"\x13discount_percentage\x18\x06 \x01(\x05R\x12discountPercentage\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vcategory_id\x18\t \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\n" +
	" \x01(\tR\fcategoryName\x12\x19\n" +
	"\bbrand_id\x18\v \x01(\tR\abrandId\x12\x1d\n" +
	"\n" +
	"brand_name\x18\f \x01(\tR\tbrandName\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xfb\x01\n" +
	"\x12GetInvoicesRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x03R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12$\n" +
	"\x0ecreated_at_gte\x18\a \x01(\tR\fcreatedAtGte\x12$\n" +
	"\x0ecreated_at_lte\x18\b \x01(\tR\fcreatedAtLte\"R\n" +
	"\x13GetInvoicesResponse\x12;\n" +
	"\binvoices\x18\x01 \x03(\v2\x1f.elasticsearchservicepb.InvoiceR\binvoices\"\xe3\x01\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xc9\x02\n" +
	"\x18ElasticsearchServiceGRPC\x12]\n" +
	"\bGetUsers\x12'.elasticsearchservicepb.GetUsersRequest\x1a(.elasticsearchservicepb.GetUsersResponse\x12f\n" +
	"\vGetProducts\x12*.elasticsearchservicepb.GetProductsRequest\x1a+.elasticsearchservicepb.GetProductsResponse\x12f\n" +
	"\vGetInvoices\x12*.elasticsearchservicepb.GetInvoicesRequest\x1a+.elasticsearchservicepb.GetInvoicesResponseB\x19Z\x17elasticsearchservicepb/b\x06proto3"

var (
	file_elasticsearch_service_proto_rawDescOnce sync.Once
	file_elasticsearch_service_proto_rawDescData []byte
)

func file_elasticsearch_service_proto_rawDescGZIP() []byte {
	file_elasticsearch_service_proto_rawDescOnce.Do(func() {
		file_elasticsearch_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_elasticsearch_service_proto_rawDesc), len(file_elasticsearch_service_proto_rawDesc)))
	})
	return file_elasticsearch_service_proto_rawDescData
}

var file_elasticsearch_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_elasticsearch_service_proto_goTypes = []any{
	(*GetUsersRequest)(nil),       // 0: elasticsearchservicepb.GetUsersRequest
	(*GetUsersResponse)(nil),      // 1: elasticsearchservicepb.GetUsersResponse
	(*User)(nil),                  // 2: elasticsearchservicepb.User
	(*GetProductsRequest)(nil),    // 3: elasticsearchservicepb.GetProductsRequest
	(*GetProductsResponse)(nil),   // 4: elasticsearchservicepb.GetProductsResponse
	(*Product)(nil),               // 5: elasticsearchservicepb.Product
	(*GetInvoicesRequest)(nil),    // 6: elasticsearchservicepb.GetInvoicesRequest
	(*GetInvoicesResponse)(nil),   // 7: elasticsearchservicepb.GetInvoicesResponse
	(*Invoice)(nil),               // 8: elasticsearchservicepb.Invoice
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_elasticsearch_service_proto_depIdxs = []int32{
	2,  // 0: elasticsearchservicepb.GetUsersResponse.users:type_name -> elasticsearchservicepb.User
	9,  // 1: elasticsearchservicepb.User.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: elasticsearchservicepb.User.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 3: elasticsearchservicepb.GetProductsResponse.products:type_name -> elasticsearchservicepb.Product
	9,  // 4: elasticsearchservicepb.Product.created_at:type_name -> google.protobuf.Timestamp
	9,  // 5: elasticsearchservicepb.Product.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 6: elasticsearchservicepb.GetInvoicesResponse.invoices:type_name -> elasticsearchservicepb.Invoice
	9,  // 7: elasticsearchservicepb.Invoice.created_at:type_name -> google.protobuf.Timestamp
	9,  // 8: elasticsearchservicepb.Invoice.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: elasticsearchservicepb.ElasticsearchServiceGRPC.GetUsers:input_type -> elasticsearchservicepb.GetUsersRequest
	3,  // 10: elasticsearchservicepb.ElasticsearchServiceGRPC.GetProducts:input_type -> elasticsearchservicepb.GetProductsRequest
	6,  // 11: elasticsearchservicepb.ElasticsearchServiceGRPC.GetInvoices:input_type -> elasticsearchservicepb.GetInvoicesRequest
	1,  // 12: elasticsearchservicepb.ElasticsearchServiceGRPC.GetUsers:output_type -> elasticsearchservicepb.GetUsersResponse
	4,  // 13: elasticsearchservicepb.ElasticsearchServiceGRPC.GetProducts:output_type -> elasticsearchservicepb.GetProductsResponse
	7,  // 14: elasticsearchservicepb.ElasticsearchServiceGRPC.GetInvoices:output_type -> elasticsearchservicepb.GetInvoicesResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_elasticsearch_service_proto_init() }
func file_elasticsearch_service_proto_init() {
	if File_elasticsearch_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_elasticsearch_service_proto_rawDesc), len(file_elasticsearch_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_elasticsearch_service_proto_goTypes,
		DependencyIndexes: file_elasticsearch_service_proto_depIdxs,
		MessageInfos:      file_elasticsearch_service_proto_msgTypes,
	}.Build()
	File_elasticsearch_service_proto = out.File
	file_elasticsearch_service_proto_goTypes = nil
	file_elasticsearch_service_proto_depIdxs = nil
}
