// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: catalog_service.proto

package catalogservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProductsRequest) Reset() {
	*x = GetAllProductsRequest{}
	mi := &file_catalog_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProductsRequest) ProtoMessage() {}

func (x *GetAllProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProductsRequest.ProtoReflect.Descriptor instead.
func (*GetAllProductsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_service_proto_rawDescGZIP(), []int{0}
}

type GetAllProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProductsResponse) Reset() {
	*x = GetAllProductsResponse{}
	mi := &file_catalog_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProductsResponse) ProtoMessage() {}

func (x *GetAllProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProductsResponse.ProtoReflect.Descriptor instead.
func (*GetAllProductsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Sex                string                 `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Price              int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPercentage int32                  `protobuf:"varint,6,opt,name=discount_percentage,json=discountPercentage,proto3" json:"discount_percentage,omitempty"`
	Stock              int32                  `protobuf:"varint,7,opt,name=stock,proto3" json:"stock,omitempty"`
	ImageUrl           string                 `protobuf:"bytes,8,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	CategoryId         string                 `protobuf:"bytes,9,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryName       string                 `protobuf:"bytes,10,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	BrandId            string                 `protobuf:"bytes,11,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	BrandName          string                 `protobuf:"bytes,12,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalog_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalog_service_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetDiscountPercentage() int32 {
	if x != nil {
		return x.DiscountPercentage
	}
	return 0
}

func (x *Product) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Product) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Product) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *Product) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *Product) GetBrandName() string {
	if x != nil {
		return x.BrandName
	}
	return ""
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_catalog_service_proto protoreflect.FileDescriptor

const file_catalog_service_proto_rawDesc = "" +
	"\n" +
	"\x15catalog_service.proto\x12\x0ecatalogservice\x1a\x1fgoogle/protobuf/timestamp.proto\"\x17\n" +
	"\x15GetAllProductsRequest\"M\n" +
	"\x16GetAllProductsResponse\x123\n" +
	"\bproducts\x18\x01 \x03(\v2\x17.catalogservice.ProductR\bproducts\"\xd1\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\tR\x03sex\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\x12/\n" +
	"\x13discount_percentage\x18\x06 \x01(\x05R\x12discountPercentage\x12\x14\n" +
	"\x05stock\x18\a \x01(\x05R\x05stock\x12\x1b\n" +
	"\timage_url\x18\b \x01(\tR\bimageUrl\x12\x1f\n" +
	"\vcategory_id\x18\t \x01(\tR\n" +
	"categoryId\x12#\n" +
	"\rcategory_name\x18\n" +
	" \x01(\tR\fcategoryName\x12\x19\n" +
	"\bbrand_id\x18\v \x01(\tR\abrandId\x12\x1d\n" +
	"\n" +
	"brand_name\x18\f \x01(\tR\tbrandName\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2u\n" +
	"\x12CatalogServiceGRPC\x12_\n" +
	"\x0eGetAllProducts\x12%.catalogservice.GetAllProductsRequest\x1a&.catalogservice.GetAllProductsResponseB\x13Z\x11catalogservicepb/b\x06proto3"

var (
	file_catalog_service_proto_rawDescOnce sync.Once
	file_catalog_service_proto_rawDescData []byte
)

func file_catalog_service_proto_rawDescGZIP() []byte {
	file_catalog_service_proto_rawDescOnce.Do(func() {
		file_catalog_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_service_proto_rawDesc), len(file_catalog_service_proto_rawDesc)))
	})
	return file_catalog_service_proto_rawDescData
}

var file_catalog_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_catalog_service_proto_goTypes = []any{
	(*GetAllProductsRequest)(nil),  // 0: catalogservice.GetAllProductsRequest
	(*GetAllProductsResponse)(nil), // 1: catalogservice.GetAllProductsResponse
	(*Product)(nil),                // 2: catalogservice.Product
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_catalog_service_proto_depIdxs = []int32{
	2, // 0: catalogservice.GetAllProductsResponse.products:type_name -> catalogservice.Product
	3, // 1: catalogservice.Product.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: catalogservice.Product.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: catalogservice.CatalogServiceGRPC.GetAllProducts:input_type -> catalogservice.GetAllProductsRequest
	1, // 4: catalogservice.CatalogServiceGRPC.GetAllProducts:output_type -> catalogservice.GetAllProductsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_catalog_service_proto_init() }
func file_catalog_service_proto_init() {
	if File_catalog_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_service_proto_rawDesc), len(file_catalog_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_service_proto_goTypes,
		DependencyIndexes: file_catalog_service_proto_depIdxs,
		MessageInfos:      file_catalog_service_proto_msgTypes,
	}.Build()
	File_catalog_service_proto = out.File
	file_catalog_service_proto_goTypes = nil
	file_catalog_service_proto_depIdxs = nil
}
