-- Bảng người dùng
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    hashed_password TEXT NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    role_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO users (full_name, email, username, hashed_password, address, role_name, created_at) VALUES
('Lê Minh Quân', 'leminhquan01@example.com', 'leminhquan01', '123', '123 Lê Lợi, Hà Nội', 'ADMIN', '2024-01-05 09:00:00'), -- id: 1
('Trần Thị Hoa', 'tranhoa02@example.com', 'tranhoa02', '123', '45 Nguyễn Huệ, TP.HCM', 'CUSTOMER', '2024-02-10 10:15:00'), -- id: 2
('Nguyễn Văn An', 'nguyenan03@example.com', 'nguyenan03', '123', '78 Phan Đình Phùng, Huế', 'CUSTOMER', '2024-03-18 14:30:00'), -- id: 3
('Phạm Quốc Huy', 'phamquochuy04@example.com', 'phamquochuy04', '123', '91 Trường Chinh, Đà Nẵng', 'CUSTOMER', '2024-04-22 08:45:00'), -- id: 4
('Lý Thị Mai', 'lymai05@example.com', 'lymai05', '123', '12 Nguyễn Văn Cừ, Cần Thơ', 'CUSTOMER', '2024-05-06 16:20:00'), -- id: 5
('Đỗ Mạnh Hùng', 'domanhhung06@example.com', 'domanhhung06', '123', '33 Hoàng Diệu, Hà Nội', 'CUSTOMER', '2024-06-11 11:00:00'), -- id: 6
('Võ Thị Kim Oanh', 'vokimoanh07@example.com', 'vokimoanh07', '123', '88 Hùng Vương, TP.HCM', 'CUSTOMER', '2024-01-03 10:00:00'), -- id: 7
('Nguyễn Hữu Tài', 'nguyentai08@example.com', 'nguyentai08', '123', '54 Điện Biên Phủ, Đà Nẵng', 'CUSTOMER', '2024-01-14 14:10:00'), -- id: 8
('Đặng Thị Hằng', 'danghang09@example.com', 'danghang09', '123', '76 Nguyễn Trãi, Hà Nội', 'CUSTOMER', '2024-01-26 12:00:00'), -- id: 9
('Hoàng Văn Tuấn', 'hoangtuan10@example.com', 'hoangtuan10', '123', '33 Trần Phú, Huế', 'CUSTOMER', '2024-02-01 15:30:00'), -- id: 10
('Phan Thị Nhung', 'phannhung11@example.com', 'phannhung11', '123', '23 Lê Thánh Tông, TP.HCM', 'CUSTOMER', '2024-02-12 13:00:00'), -- id: 11
('Nguyễn Văn Toàn', 'nguyentoan12@example.com', 'nguyentoan12', '123', '18 Hòa Bình, Cần Thơ', 'CUSTOMER', '2024-02-19 17:00:00'), -- id: 12
('Lê Thị Hạnh', 'lehanh13@example.com', 'lehanh13', '123', '65 Nguyễn Văn Linh, Đà Nẵng', 'CUSTOMER', '2024-02-25 08:50:00'), -- id: 13
('Trần Thanh Tùng', 'trantung14@example.com', 'trantung14', '123', '21 Trần Quý Cáp, Hà Nội', 'CUSTOMER', '2024-03-03 16:40:00'), -- id: 14
('Ngô Đức Anh', 'ngoducanh15@example.com', 'ngoducanh15', '123', '17 Cách Mạng Tháng 8, TP.HCM', 'CUSTOMER', '2024-03-09 14:00:00'), -- id: 15
('Bùi Thị Lan', 'builan16@example.com', 'builan16', '123', '46 Hai Bà Trưng, Huế', 'CUSTOMER', '2024-03-15 11:10:00'), -- id: 16
('Đỗ Văn Thành', 'dothanh17@example.com', 'dothanh17', '123', '99 Võ Văn Tần, Đà Nẵng', 'CUSTOMER', '2024-03-23 10:30:00'), -- id: 17
('Lê Mai Phương', 'lemaiphuong18@example.com', 'lemaiphuong18', '123', '102 Nguyễn Du, Hà Nội', 'CUSTOMER', '2024-03-30 09:40:00'), -- id: 18
('Phạm Thanh Trúc', 'phamtruc19@example.com', 'phamtruc19', '123', '75 Nguyễn Thiện Thuật, TP.HCM', 'CUSTOMER', '2024-04-04 16:00:00'), -- id: 19
('Nguyễn Quốc Bảo', 'nguyenquocbao20@example.com', 'nguyenquocbao20', '123', '12 Nguyễn Văn Thoại, Đà Nẵng', 'CUSTOMER', '2024-04-11 08:00:00'), -- id: 20
('Trịnh Thị Thu', 'trinhthu21@example.com', 'trinhthu21', '123', '58 Nguyễn Trãi, Cần Thơ', 'CUSTOMER', '2024-04-17 17:10:00'), -- id: 21
('Lý Minh Tuấn', 'lyminhtuan22@example.com', 'lyminhtuan22', '123', '35 Nguyễn Đình Chiểu, Hà Nội', 'CUSTOMER', '2024-04-25 15:00:00'), -- id: 22
('Mai Văn Hoàng', 'maivanhoang23@example.com', 'maivanhoang23', '123', '48 Phan Xích Long, TP.HCM', 'CUSTOMER', '2024-05-01 14:40:00'), -- id: 23
('Nguyễn Thị Ngọc', 'nguyenngoc24@example.com', 'nguyenngoc24', '123', '89 Nguyễn Công Trứ, Huế', 'CUSTOMER', '2024-05-08 12:15:00'), -- id: 24
('Phan Văn Dũng', 'phandung25@example.com', 'phandung25', '123', '51 Điện Biên Phủ, Hà Nội', 'CUSTOMER', '2024-05-14 10:45:00'), -- id: 25
('Trần Hải Nam', 'tranhnam26@example.com', 'tranhnam26', '123', '17 Nguyễn Văn Cừ, TP.HCM', 'CUSTOMER', '2024-05-21 09:20:00'), -- id: 26
('Đinh Thị Yến', 'dinhyen27@example.com', 'dinhyen27', '123', '33 Trần Hưng Đạo, Hà Nội', 'CUSTOMER', '2024-05-27 15:10:00'), -- id: 27
('Lưu Văn Phát', 'luuphat28@example.com', 'luuphat28', '123', '91 Nguyễn Khuyến, Huế', 'CUSTOMER', '2024-06-03 14:00:00'), -- id: 28
('Nguyễn Thị Bích Ngọc', 'ngocbich29@example.com', 'ngocbich29', '123', '22 Nguyễn Văn Linh, Đà Nẵng', 'CUSTOMER', '2024-06-10 11:45:00'), -- id: 29
('Phạm Quang Hòa', 'phamhoa30@example.com', 'phamhoa30', '123', '45 Lý Thường Kiệt, Cần Thơ', 'CUSTOMER', '2024-06-17 17:30:00'), -- id: 30
('Trương Mỹ Linh', 'truonglinh31@example.com', 'truonglinh31', '123', '18 Hoàng Văn Thụ, Hà Nội', 'CUSTOMER', '2024-06-24 13:20:00'), -- id: 31
('Bùi Minh Tú', 'buimintu32@example.com', 'buimintu32', '123', '59 Phạm Văn Đồng, TP.HCM', 'CUSTOMER', '2024-07-01 16:00:00'), -- id: 32
('Lê Thị Kim Dung', 'lekimdung33@example.com', 'lekimdung33', '123', '66 Nguyễn Trãi, Đà Nẵng', 'CUSTOMER', '2024-07-09 10:15:00'), -- id: 33
('Hoàng Gia Bảo', 'hoanggia34@example.com', 'hoanggia34', '123', '33 Bạch Đằng, Huế', 'CUSTOMER', '2024-07-15 15:45:00'), -- id: 34
('Nguyễn Văn Phúc', 'nguyenphuc35@example.com', 'nguyenphuc35', '123', '71 Hùng Vương, TP.HCM', 'CUSTOMER', '2024-07-23 11:10:00'), -- id: 35
('Võ Thị Thanh Huyền', 'vothanhhuyen36@example.com', 'vothanhhuyen36', '123', '40 Trần Phú, Cần Thơ', 'CUSTOMER', '2024-07-30 09:30:00'), -- id: 36
('Đặng Quốc Khánh', 'dangquockhanh37@example.com', 'dangquockhanh37', '123', '15 Lê Hồng Phong, Hà Nội', 'CUSTOMER', '2024-08-06 08:50:00'), -- id: 37
('Nguyễn Nhật Nam', 'nguyennhatnam38@example.com', 'nguyennhatnam38', '123', '84 Cách Mạng Tháng 8, TP.HCM', 'CUSTOMER', '2024-08-12 16:10:00'), -- id: 38
('Lý Thị Hường', 'lyhuong39@example.com', 'lyhuong39', '123', '39 Phan Đăng Lưu, Đà Nẵng', 'CUSTOMER', '2024-08-18 14:30:00'), -- id: 39
('Trần Minh Hiếu', 'tranhieu40@example.com', 'tranhieu40', '123', '92 Nguyễn Văn Thoại, Huế', 'CUSTOMER', '2024-08-24 10:45:00'), -- id: 40
('Đỗ Hải Yến', 'dohaiyen41@example.com', 'dohaiyen41', '123', '29 Phạm Ngũ Lão, Hà Nội', 'CUSTOMER', '2024-09-01 13:40:00'), -- id: 41
('Nguyễn Huy Hoàng', 'nguyenhuyhoang42@example.com', 'nguyenhuyhoang42', '123', '51 Trần Quốc Toản, TP.HCM', 'CUSTOMER', '2024-09-08 15:25:00'), -- id: 42
('Lê Quang Vinh', 'lequangvinh43@example.com', 'lequangvinh43', '123', '14 Lê Văn Sỹ, Đà Nẵng', 'CUSTOMER', '2024-09-14 11:00:00'), -- id: 43
('Phạm Kim Ngân', 'phamkimngan44@example.com', 'phamkimngan44', '123', '62 Nguyễn Văn Cừ, Cần Thơ', 'CUSTOMER', '2024-09-22 09:10:00'), -- id: 44
('Bùi Nhật Linh', 'buinhatlinh45@example.com', 'buinhatlinh45', '123', '47 Lý Chính Thắng, Huế', 'CUSTOMER', '2024-10-01 08:40:00'), -- id: 45
('Nguyễn Thanh Lam', 'nguyenlam46@example.com', 'nguyenlam46', '123', '79 Nguyễn Đình Chiểu, TP.HCM', 'CUSTOMER', '2024-10-10 14:35:00'), -- id: 46
('Trịnh Hoàng Phúc', 'trinhphuc47@example.com', 'trinhphuc47', '123', '25 Nguyễn Văn Linh, Hà Nội', 'CUSTOMER', '2024-10-17 12:25:00'), -- id: 47
('Phan Thị Kim Cúc', 'phamkimcuc48@example.com', 'phamkimcuc48', '123', '38 Nguyễn Văn Trỗi, Đà Nẵng', 'CUSTOMER', '2024-10-26 13:45:00'), -- id: 48
('Đoàn Thanh Sơn', 'doanson49@example.com', 'doanson49', '123', '90 Nguyễn Trãi, TP.HCM', 'CUSTOMER', '2024-11-03 16:20:00'), -- id: 49
('Trần Thị Diễm', 'trandiem50@example.com', 'trandiem50', '123', '27 Trần Hưng Đạo, Huế', 'CUSTOMER', '2024-11-11 10:50:00'); -- id: 50

-- Bảng danh mục sản phẩm
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO categories (name, created_at) VALUES
('Áo thun', '2024-01-10 10:00:00'), -- id: 1
('Áo sơ mi', '2024-02-15 14:30:00'), -- id: 2
('Áo khoác', '2024-03-20 09:15:00'), -- id: 3
('Quần jeans', '2024-04-05 16:45:00'), -- id: 4
('Quần short', '2024-05-12 11:10:00'), -- id: 5
('Giày thể thao', '2024-06-18 13:50:00'), -- id: 6
('Giày boot', '2024-07-22 08:30:00'), -- id: 7
('Váy đầm', '2024-08-28 15:00:00'), -- id: 8
('Kính mắt', '2024-09-05 10:25:00'), -- id: 9
('Túi xách', '2024-10-10 17:40:00'); -- id: 10

-- Bảng thương hiệu sản phẩm
CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO brands (name, description, created_at) VALUES
('Nike', 'Thương hiệu nổi tiếng toàn cầu chuyên về giày thể thao và trang phục thể thao.', '2024-01-12 10:00:00'), -- id: 1
('Adidas', 'Thương hiệu thời trang thể thao đến từ Đức, nổi bật với các mẫu giày và áo thể thao.', '2024-02-18 14:30:00'), -- id: 2
('Puma', 'Puma cung cấp sản phẩm thể thao với thiết kế năng động và trẻ trung.', '2024-03-05 09:45:00'), -- id: 3
('Levis', 'Thương hiệu nổi tiếng với các sản phẩm quần jeans chất lượng cao.', '2024-03-25 16:00:00'), -- id: 4
('Zara', 'Zara chuyên về thời trang nhanh, cập nhật xu hướng liên tục với mức giá hợp lý.', '2024-04-10 11:20:00'), -- id: 5
('H&M', 'Thời trang bình dân, đa dạng mẫu mã cho mọi đối tượng và phong cách.', '2024-05-02 13:15:00'), -- id: 6
('Gucci', 'Thương hiệu cao cấp của Ý, nổi tiếng với các thiết kế sang trọng và đẳng cấp.', '2024-06-14 15:40:00'), -- id: 7
('Uniqlo', 'Uniqlo cung cấp các sản phẩm thời trang cơ bản, bền bỉ và tiện dụng.', '2024-07-08 08:55:00'), -- id: 8
('Converse', 'Thương hiệu giày thể thao biểu tượng với phong cách cổ điển, được giới trẻ ưa chuộng.', '2024-08-19 10:10:00'), -- id: 9
('Bitis', 'Thương hiệu Việt Nam nổi bật với các sản phẩm giày dép bền đẹp và giá cả hợp lý.', '2024-09-30 17:25:00'); -- id: 10

-- Bảng sản phẩm
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    sex VARCHAR(255) NOT NULL,
    price BIGINT NOT NULL,
    discount_percentage INT NOT NULL,
    stock INT NOT NULL,
    image_url TEXT NOT NULL,
    category_id BIGINT NOT NULL REFERENCES categories(id),
    brand_id BIGINT NOT NULL REFERENCES brands(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO products (name, description, sex, price, discount_percentage, stock, image_url, category_id, brand_id, created_at) VALUES
('Túi xách da', 'Áo khoác mùa đông, giữ ấm tốt cho cơ thể.', 'UNISEX', 430238, 42, 64, 'https://example.com/images/12.jpg', 4, 3, '2024-06-05 00:00:00'), -- id: 1
('Quần dài kaki', 'Áo hoodie thể thao thoải mái.', 'MALE', 285038, 27, 51, 'https://example.com/images/36.jpg', 9, 2, '2024-10-17 00:00:00'), -- id: 2
('Giày boot nam', 'Áo khoác da cao cấp cho mùa lạnh.', 'FEMALE', 948931, 48, 58, 'https://example.com/images/37.jpg', 9, 3, '2024-07-23 00:00:00'), -- id: 3
('Áo polo', 'Giày boot da sang trọng cho mùa đông.', 'FEMALE', 593538, 1, 79, 'https://example.com/images/27.jpg', 8, 2, '2024-01-27 00:00:00'), -- id: 4
('Áo sơ mi công sở', 'Váy đầm dạ hội đẹp và sang trọng.', 'UNISEX', 288631, 32, 88, 'https://example.com/images/66.jpg', 1, 9, '2024-11-12 00:00:00'), -- id: 5
('Áo thun thể thao', 'Áo sơ mi công sở với thiết kế thanh lịch.', 'MALE', 368347, 20, 60, 'https://example.com/images/19.jpg', 2, 1, '2024-08-02 00:00:00'), -- id: 6
('Áo khoác da', 'Áo khoác da cao cấp cho mùa lạnh.', 'UNISEX', 499938, 35, 55, 'https://example.com/images/55.jpg', 3, 7, '2024-09-01 00:00:00'), -- id: 7
('Quần jeans nữ', 'Quần jeans nữ đẹp và dễ phối đồ.', 'FEMALE', 451237, 15, 48, 'https://example.com/images/23.jpg', 4, 4, '2024-07-19 00:00:00'), -- id: 8
('Giày thể thao Nike', 'Giày thể thao Nike, phong cách thể thao, thoải mái.', 'MALE', 631023, 25, 70, 'https://example.com/images/62.jpg', 6, 1, '2024-05-10 00:00:00'), -- id: 9
('Váy đầm dạ hội', 'Váy đầm dạ hội đẹp và sang trọng.', 'FEMALE', 799999, 30, 40, 'https://example.com/images/13.jpg', 8, 9, '2024-03-12 00:00:00'), -- id: 1
('Kính mát thời trang', 'Kính mắt thể thao bảo vệ mắt khỏi ánh sáng mặt trời.', 'UNISEX', 128500, 5, 120, 'https://example.com/images/21.jpg', 9, 3, '2024-10-25 00:00:00'), -- id: 10
('Áo khoác mùa đông', 'Áo khoác mùa đông, giữ ấm tốt cho cơ thể.', 'FEMALE', 850012, 40, 63, 'https://example.com/images/5.jpg', 3, 5, '2024-12-01 00:00:00'), -- id: 11
('Quần jogger', 'Quần jogger thời trang, dễ phối đồ.', 'MALE', 379295, 18, 92, 'https://example.com/images/33.jpg', 4, 8, '2024-05-20 00:00:00'), -- id: 12
('Giày thể thao Adidas', 'Giày thể thao Adidas, bền bỉ và dễ chịu.', 'MALE', 724932, 20, 72, 'https://example.com/images/56.jpg', 6, 2, '2024-06-15 00:00:00'), -- id: 13
('Giày boot da', 'Giày boot da sang trọng cho mùa đông.', 'FEMALE', 883416, 50, 33, 'https://example.com/images/4.jpg', 7, 3, '2024-11-05 00:00:00'), -- id: 14
('Túi xách công sở', 'Túi xách công sở dành cho những người đi làm.', 'UNISEX', 1500000, 18, 70, 'https://example.com/images/76.jpg', 10, 3, '2024-07-22 00:00:00'), -- id: 15
('Váy đầm công sở', 'Váy đầm công sở thanh lịch, dễ phối.', 'FEMALE', 503670, 10, 85, 'https://example.com/images/70.jpg', 8, 1, '2024-06-03 00:00:00'), -- id: 16
('Áo len', 'Áo len ấm áp cho mùa lạnh.', 'MALE', 250237, 15, 61, 'https://example.com/images/19.jpg', 2, 4, '2024-07-10 00:00:00'), -- id: 17
('Áo hoodie', 'Áo hoodie thể thao thoải mái.', 'UNISEX', 345890, 23, 58, 'https://example.com/images/34.jpg', 2, 6, '2024-09-10 00:00:00'), -- id: 18
('Áo khoác bomber', 'Áo khoác bomber phong cách trẻ trung.', 'MALE', 530201, 12, 55, 'https://example.com/images/44.jpg', 5, 2, '2024-05-07 00:00:00'), -- id: 19
('Quần short nữ', 'Quần short nữ thoải mái cho mùa hè.', 'FEMALE', 220450, 30, 79, 'https://example.com/images/3.jpg', 4, 9, '2024-12-04 00:00:00'), -- id: 20
('Quần kaki', 'Quần dài kaki phù hợp với nhiều hoàn cảnh.', 'UNISEX', 499203, 18, 60, 'https://example.com/images/16.jpg', 1, 10, '2024-06-20 00:00:00'), -- id: 21
('Áo khoác vải', 'Áo khoác vải nhẹ cho mùa xuân.', 'MALE', 389786, 30, 80, 'https://example.com/images/28.jpg', 3, 7, '2024-06-10 00:00:00'), -- id: 22
('Giày thể thao Uniqlo', 'Giày thể thao Uniqlo bền và nhẹ.', 'UNISEX', 475389, 22, 67, 'https://example.com/images/50.jpg', 6, 8, '2024-08-15 00:00:00'), -- id: 23
('Váy đầm liền thân', 'Váy đầm liền thân thanh lịch cho cô nàng công sở.', 'FEMALE', 299999, 15, 49, 'https://example.com/images/41.jpg', 8, 5, '2024-07-28 00:00:00'), -- id: 24
('Quần shorts thể thao', 'Quần shorts thể thao thoải mái cho mùa hè.', 'MALE', 220398, 18, 60, 'https://example.com/images/32.jpg', 5, 6, '2024-04-15 00:00:00'), -- id: 25
('Kính mát Gucci', 'Kính mát Gucci sang trọng và đẳng cấp.', 'UNISEX', 2000000, 15, 30, 'https://example.com/images/69.jpg', 9, 7, '2024-09-20 00:00:00'), -- id: 26
('Áo thun nữ', 'Áo thun nữ phù hợp với nhiều phong cách.', 'FEMALE', 120345, 25, 55, 'https://example.com/images/22.jpg', 1, 2, '2024-06-01 00:00:00'), -- id: 27
('Kính mắt Uniqlo', 'Kính mắt Uniqlo mang phong cách hiện đại và trẻ trung.', 'UNISEX', 400000, 20, 50, 'https://example.com/images/68.jpg', 9, 8, '2024-07-05 00:00:00'), -- id: 28
('Túi xách nam', 'Túi xách nam, thiết kế đơn giản nhưng tinh tế.', 'MALE', 950000, 30, 90, 'https://example.com/images/75.jpg', 10, 9, '2024-06-02 00:00:00'), -- id: 29
('Quần jeans slimfit', 'Quần jeans slimfit dễ phối đồ.', 'MALE', 410537, 30, 70, 'https://example.com/images/18.jpg', 4, 4, '2024-05-17 00:00:00'), -- id: 30
('Kính mắt nữ Zara', 'Kính mắt nữ Zara, kiểu dáng thời trang.', 'FEMALE', 150000, 25, 100, 'https://example.com/images/71.jpg', 9, 5, '2024-08-18 00:00:00'), -- id: 31
('Áo khoác dáng dài', 'Áo khoác dáng dài giúp giữ ấm và phong cách.', 'UNISEX', 622131, 35, 64, 'https://example.com/images/60.jpg', 3, 1, '2024-07-02 00:00:00'), -- id: 32
('Giày sneaker nữ', 'Giày sneaker nữ thời trang và thoải mái.', 'FEMALE', 509876, 50, 45, 'https://example.com/images/58.jpg', 6, 8, '2024-08-18 00:00:00'), -- id: 33
('Áo sơ mi nam', 'Áo sơ mi nam công sở, thanh lịch.', 'MALE', 379412, 20, 58, 'https://example.com/images/53.jpg', 2, 3, '2024-05-01 00:00:00'), -- id: 34
('Áo khoác bomber nam', 'Áo khoác bomber nam, phong cách và mạnh mẽ.', 'MALE', 689031, 15, 53, 'https://example.com/images/46.jpg', 3, 1, '2024-03-28 00:00:00'), -- id: 35
('Giày boots nữ', 'Giày boots nữ thời trang, dễ dàng kết hợp trang phục.', 'FEMALE', 102309, 40, 75, 'https://example.com/images/35.jpg', 7, 5, '2024-09-10 00:00:00'), -- id: 36
('Áo thun nam', 'Áo thun nam thể thao, thoải mái cho các hoạt động.', 'MALE', 349987, 22, 65, 'https://example.com/images/39.jpg', 1, 2, '2024-07-20 00:00:00'), -- id: 37
('Quần jean nam', 'Quần jean nam chất liệu bền đẹp.', 'MALE', 449032, 18, 60, 'https://example.com/images/24.jpg', 4, 1, '2024-04-25 00:00:00'), -- id: 38
('Túi xách Gucci', 'Túi xách Gucci cao cấp, sang trọng và bền bỉ.', 'FEMALE', 3500000, 20, 50, 'https://example.com/images/72.jpg', 10, 7, '2024-07-10 00:00:00'), -- id: 39
('Áo sơ mi nữ', 'Áo sơ mi nữ thanh lịch cho môi trường công sở.', 'FEMALE', 239853, 20, 77, 'https://example.com/images/63.jpg', 2, 7, '2024-08-05 00:00:00'), -- id: 40
('Quần jogger nam', 'Quần jogger nam, phù hợp cho các hoạt động thể thao.', 'MALE', 330205, 12, 63, 'https://example.com/images/64.jpg', 5, 9, '2024-06-07 00:00:00'), -- id: 41
('Giày cao gót nữ', 'Giày cao gót nữ thời trang, sang trọng.', 'FEMALE', 765437, 30, 55, 'https://example.com/images/49.jpg', 6, 2, '2024-09-30 00:00:00'), -- id: 42
('Túi xách nữ thời trang', 'Túi xách nữ thời trang, thích hợp cho mọi dịp.', 'FEMALE', 1200000, 10, 80, 'https://example.com/images/74.jpg', 10, 8, '2024-08-05 00:00:00'), -- id: 43
('Váy đầm búp bê', 'Váy đầm búp bê phù hợp với các cô nàng yêu thích phong cách dễ thương.', 'FEMALE', 189876, 27, 61, 'https://example.com/images/30.jpg', 8, 4, '2024-06-23 00:00:00'), -- id: 44
('Áo khoác vest', 'Áo khoác vest phù hợp cho những buổi họp mặt trang trọng.', 'MALE', 499876, 20, 62, 'https://example.com/images/51.jpg', 3, 2, '2024-05-18 00:00:00'), -- id: 45
('Giày sandal nữ', 'Giày sandal nữ đơn giản nhưng thời trang.', 'FEMALE', 285634, 17, 90, 'https://example.com/images/66.jpg', 6, 6, '2024-07-30 00:00:00'), -- id: 46
('Áo thun ngắn tay', 'Áo thun ngắn tay thoải mái cho mùa hè.', 'UNISEX', 170254, 25, 80, 'https://example.com/images/37.jpg', 1, 9, '2024-08-02 00:00:00'), -- id: 47
('Túi xách nữ cao cấp', 'Túi xách nữ cao cấp, thiết kế thanh lịch và sang trọng.', 'FEMALE', 2500000, 20, 50, 'https://example.com/images/78.jpg', 10, 5, '2024-06-28 00:00:00'), -- id: 48
('Quần jean nữ', 'Quần jean nữ với thiết kế ôm sát cơ thể.', 'FEMALE', 389723, 18, 50, 'https://example.com/images/61.jpg', 4, 5, '2024-06-11 00:00:00'), -- id: 49
('Áo sơ mi công sở nam', 'Áo sơ mi công sở nam, phù hợp với môi trường văn phòng.', 'MALE', 359887, 30, 62, 'https://example.com/images/25.jpg', 2, 3, '2024-05-23 00:00:00'), -- id: 50
('Giày thể thao nam', 'Giày thể thao nam chắc chắn và bền bỉ.', 'MALE', 534763, 12, 58, 'https://example.com/images/45.jpg', 6, 2, '2024-07-10 00:00:00'), -- id: 51
('Váy đầm công sở nữ', 'Váy đầm công sở thanh lịch, dễ phối.', 'FEMALE', 469220, 15, 80, 'https://example.com/images/29.jpg', 8, 10, '2024-08-18 00:00:00'), -- id: 52
('Áo khoác ngoài', 'Áo khoác ngoài có thể phối với nhiều trang phục.', 'UNISEX', 388786, 20, 55, 'https://example.com/images/47.jpg', 3, 1, '2024-07-18 00:00:00'), -- id: 53
('Quần short nam', 'Quần short nam cho các hoạt động thể thao.', 'MALE', 230958, 40, 90, 'https://example.com/images/52.jpg', 5, 2, '2024-06-22 00:00:00'), -- id: 54
('Giày thể thao nữ', 'Giày thể thao nữ thời trang và dễ chịu.', 'FEMALE', 553789, 22, 50, 'https://example.com/images/64.jpg', 6, 5, '2024-08-20 00:00:00'), -- id: 55
('Áo thun đồng phục', 'Áo thun đồng phục cho các tổ chức, nhóm.', 'UNISEX', 160245, 30, 75, 'https://example.com/images/54.jpg', 1, 3, '2024-09-25 00:00:00'), -- id: 56
('Giày thể thao Nike mới', 'Giày thể thao Nike, kiểu dáng mới cho năm 2024.', 'MALE', 734921, 12, 65, 'https://example.com/images/26.jpg', 6, 1, '2024-07-12 00:00:00'), -- id: 57
('Áo khoác dù', 'Áo khoác dù nhẹ và chống gió.', 'UNISEX', 469889, 18, 60, 'https://example.com/images/56.jpg', 3, 6, '2024-08-05 00:00:00'), -- id: 58
('Giày boot da nam', 'Giày boot da nam mạnh mẽ và bền bỉ.', 'MALE', 785234, 15, 50, 'https://example.com/images/48.jpg', 7, 2, '2024-05-13 00:00:00'), -- id: 59
('Áo hoodie nữ', 'Áo hoodie nữ thiết kế trẻ trung và năng động.', 'FEMALE', 455890, 20, 85, 'https://example.com/images/57.jpg', 2, 5, '2024-09-10 00:00:00'), -- id: 60
('Kính mắt thời trang', 'Kính mắt thời trang dành cho những ngày nắng.', 'UNISEX', 250000, 25, 80, 'https://example.com/images/67.jpg', 9, 5, '2024-08-10 00:00:00'), -- id: 61
('Túi xách da nam', 'Túi xách da nam cao cấp, bền và đẹp.', 'MALE', 2000000, 25, 60, 'https://example.com/images/77.jpg', 10, 4, '2024-09-01 00:00:00'), -- id: 62
('Kính mắt nam Adidas', 'Kính mắt nam Adidas dành cho thể thao.', 'MALE', 350000, 30, 70, 'https://example.com/images/70.jpg', 9, 2, '2024-06-15 00:00:00'), -- id: 63
('Túi xách thể thao', 'Túi xách thể thao cho các hoạt động ngoài trời.', 'UNISEX', 800000, 15, 65, 'https://example.com/images/73.jpg', 10, 6, '2024-05-25 00:00:00'); -- id: 64

-- Bảng chi tiết mặt hàng trong giỏ hàng
CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    quantity INT NOT NULL
);
INSERT INTO cart_items(user_id, product_id, quantity) VALUES
(2, 1, 2), -- id: 1
(2, 2, 1), -- id: 2
(2, 3, 3), -- id: 3
(2, 4, 1), -- id: 4
(3, 5, 2), -- id: 5
(3, 6, 1), -- id: 6
(3, 7, 3), -- id: 7
(3, 8, 2), -- id: 8
(4, 9, 1), -- id: 9
(4, 10, 3), -- id: 10
(4, 11, 2), -- id: 11
(4, 12, 1), -- id: 12
(4, 13, 1), -- id: 13
(5, 14, 2), -- id: 14
(5, 15, 1), -- id: 15
(5, 16, 3), -- id: 16
(5, 17, 2), -- id: 17
(5, 18, 1), -- id: 18
(6, 19, 2), -- id: 19
(6, 20, 1), -- id: 20
(6, 21, 3), -- id: 21
(6, 22, 2), -- id: 22
(7, 23, 1), -- id: 23
(7, 24, 3), -- id: 24
(7, 25, 2), -- id: 25
(7, 26, 1), -- id: 26
(7, 27, 2), -- id: 27
(7, 28, 3), -- id: 28
(7, 29, 1), -- id: 29
(8, 30, 1), -- id: 30
(8, 31, 2), -- id: 31
(8, 32, 1), -- id: 32
(8, 33, 3), -- id: 33
(8, 34, 2), -- id: 34
(8, 35, 1), -- id: 35
(8, 36, 2), -- id: 36
(9, 37, 3), -- id: 37
(9, 38, 2), -- id: 38
(9, 39, 1), -- id: 39
(9, 40, 2), -- id: 40
(9, 41, 1), -- id: 41
(9, 42, 3), -- id: 42
(9, 43, 1), -- id: 43
(10, 44, 2), -- id: 44
(10, 45, 1), -- id: 45
(10, 46, 2), -- id: 46
(10, 47, 3), -- id: 47
(10, 48, 1), -- id: 48
(10, 49, 3), -- id: 49
(10, 50, 2), -- id: 50
(10, 51, 1), -- id: 51
(10, 52, 3), -- id: 52
(11, 53, 2), -- id: 53
(11, 54, 1), -- id: 54
(11, 55, 2), -- id: 55
(12, 56, 3), -- id: 56
(12, 57, 2), -- id: 57
(12, 58, 1), -- id: 58
(13, 59, 1), -- id: 59
(13, 60, 2), -- id: 60
(13, 61, 3), -- id: 61
(14, 62, 1), -- id: 62
(14, 63, 2), -- id: 63
(14, 64, 1), -- id: 64
(15, 1, 3), -- id: 65
(15, 2, 2), -- id: 66
(15, 3, 1), -- id: 67
(15, 4, 2), -- id: 68
(16, 5, 3), -- id: 69
(16, 6, 1), -- id: 70
(16, 7, 2), -- id: 71
(16, 8, 3), -- id: 72
(17, 9, 1), -- id: 73
(17, 10, 2), -- id: 74
(17, 11, 3), -- id: 75
(18, 12, 2), -- id: 76
(18, 13, 3), -- id: 77
(18, 14, 1), -- id: 78
(19, 15, 2), -- id: 79
(19, 16, 3), -- id: 80
(19, 17, 1), -- id: 81
(20, 18, 1), -- id: 82
(20, 19, 2), -- id: 83
(20, 20, 1), -- id: 84
(21, 21, 3), -- id: 85
(21, 22, 1), -- id: 86
(21, 23, 2), -- id: 87
(22, 24, 1), -- id: 88
(22, 25, 2), -- id: 89
(22, 26, 1), -- id: 90
(23, 27, 2), -- id: 91
(23, 28, 1), -- id: 92
(23, 29, 3), -- id: 93
(24, 30, 1), -- id: 94
(24, 31, 3), -- id: 95
(24, 32, 2), -- id: 96
(25, 33, 2), -- id: 97
(25, 34, 1), -- id: 98
(25, 35, 3), -- id: 99
(25, 36, 2), -- id: 100
(25, 37, 1), -- id: 101
(26, 38, 1), -- id: 102
(26, 39, 2), -- id: 103
(26, 40, 3), -- id: 104
(26, 41, 1), -- id: 105
(27, 42, 2), -- id: 106
(27, 43, 1), -- id: 107
(27, 44, 3), -- id: 108
(27, 45, 1), -- id: 109
(28, 46, 2), -- id: 110
(28, 47, 3), -- id: 111
(28, 48, 1), -- id: 112
(28, 49, 2), -- id: 113
(28, 50, 3), -- id: 114
(29, 51, 1), -- id: 115
(29, 52, 3), -- id: 116
(29, 53, 2), -- id: 117
(29, 54, 1), -- id: 118
(30, 55, 2), -- id: 119
(30, 56, 3), -- id: 120
(30, 57, 1), -- id: 121
(30, 58, 2), -- id: 122
(31, 59, 3), -- id: 123
(31, 60, 1), -- id: 124
(31, 61, 2), -- id: 125
(32, 62, 1), -- id: 126
(32, 63, 2), -- id: 127
(32, 64, 3), -- id: 128
(33, 1, 2), -- id: 129
(33, 2, 3), -- id: 130
(33, 3, 1), -- id: 131
(34, 4, 2), -- id: 132
(34, 5, 3), -- id: 133
(34, 6, 1), -- id: 134
(35, 7, 2), -- id: 135
(35, 8, 3), -- id: 136
(35, 9, 1), -- id: 137
(35, 10, 3), -- id: 138
(36, 11, 2), -- id: 139
(36, 12, 1), -- id: 140
(36, 13, 3), -- id: 141
(37, 14, 2), -- id: 142
(37, 15, 1), -- id: 143
(37, 16, 3), -- id: 144
(38, 17, 2), -- id: 145
(38, 18, 3), -- id: 146
(38, 19, 1), -- id: 147
(39, 20, 3), -- id: 148
(39, 21, 2), -- id: 149
(39, 22, 1), -- id: 150
(40, 23, 2), -- id: 151
(40, 24, 3), -- id: 152
(40, 25, 1), -- id: 153
(41, 26, 2), -- id: 154
(41, 27, 1), -- id: 155
(41, 28, 3), -- id: 156
(42, 29, 1), -- id: 157
(42, 30, 3), -- id: 158
(42, 31, 2), -- id: 159
(43, 32, 1), -- id: 160
(43, 33, 2), -- id: 161
(43, 34, 3), -- id: 162
(44, 35, 1), -- id: 163
(44, 36, 3), -- id: 164
(44, 37, 2), -- id: 165
(45, 38, 2), -- id: 166
(45, 39, 1), -- id: 167
(45, 40, 3), -- id: 168
(46, 41, 1), -- id: 169
(46, 42, 3), -- id: 170
(46, 43, 2), -- id: 171
(47, 44, 1), -- id: 172
(47, 45, 2), -- id: 173
(47, 46, 3), -- id: 174
(48, 47, 2), -- id: 175
(48, 48, 1), -- id: 176
(48, 49, 3), -- id: 177
(49, 50, 2), -- id: 178
(49, 51, 1), -- id: 179
(49, 52, 3), -- id: 180
(50, 53, 1), -- id: 181
(50, 54, 2), -- id: 182
(50, 55, 3); -- id: 183

-- Bảng hóa đơn
CREATE TABLE invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    total_amount BIGINT NOT NULL,
    `status` VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO invoices(user_id, total_amount, status, created_at) VALUES
(2, 120000, 'DONE', '2024-01-15 10:20:00'), -- id: 1
(2, 80000, 'DONE', '2024-02-02 14:30:00'), -- id: 2
(2, 150000, 'DONE', '2024-03-05 11:45:00'), -- id: 3
(2, 100000, 'DONE', '2024-04-12 16:00:00'), -- id: 4
(3, 130000, 'DONE', '2024-05-22 09:00:00'), -- id: 5
(3, 200000, 'DONE', '2024-01-20 15:00:00'), -- id: 6
(3, 180000, 'DONE', '2024-02-10 12:00:00'), -- id: 7
(3, 220000, 'DONE', '2024-03-25 17:10:00'), -- id: 8
(3, 170000, 'DONE', '2024-04-15 14:50:00'), -- id: 9
(4, 150000, 'DONE', '2024-05-30 16:45:00'), -- id: 10
(4, 190000, 'DONE', '2024-01-25 13:00:00'), -- id: 11
(4, 210000, 'DONE', '2024-02-18 08:20:00'), -- id: 12
(4, 160000, 'DONE', '2024-03-05 10:40:00'), -- id: 13
(4, 140000, 'DONE', '2024-04-10 17:00:00'), -- id: 14
(4, 175000, 'DONE', '2024-05-17 11:35:00'), -- id: 15
(4, 125000, 'DONE', '2024-01-30 11:10:00'), -- id: 16
(5, 160000, 'DONE', '2024-02-25 14:20:00'), -- id: 17
(5, 180000, 'DONE', '2024-03-15 16:55:00'), -- id: 18
(5, 190000, 'DONE', '2024-04-18 13:40:00'), -- id: 19
(5, 210000, 'DONE', '2024-05-25 09:50:00'), -- id: 20
(5, 220000, 'DONE', '2024-01-10 12:30:00'), -- id: 21
(5, 130000, 'DONE', '2024-02-05 15:00:00'), -- id: 22
(5, 160000, 'DONE', '2024-03-20 17:25:00'), -- id: 23
(5, 110000, 'DONE', '2024-04-02 14:10:00'), -- id: 24
(5, 140000, 'DONE', '2024-05-15 08:40:00'), -- id: 25
(6, 180000, 'DONE', '2024-02-12 10:40:00'), -- id: 26
(6, 210000, 'DONE', '2024-03-10 11:50:00'), -- id: 27
(6, 200000, 'DONE', '2024-04-05 13:30:00'), -- id: 28
(6, 170000, 'DONE', '2024-05-22 17:15:00'), -- id: 29
(7, 150000, 'PENDING', '2024-02-22 12:50:00'), -- id: 30
(7, 120000, 'DONE', '2024-03-12 16:00:00'), -- id: 31
(7, 140000, 'PENDING', '2024-04-20 10:25:00'), -- id: 32
(7, 170000, 'CANCEL', '2024-05-07 13:40:00'), -- id: 33
(7, 180000, 'PENDING', '2024-05-25 14:30:00'), -- id: 34
(8, 160000, 'DONE', '2024-02-03 15:20:00'), -- id: 35
(8, 190000, 'PENDING', '2024-03-22 08:10:00'), -- id: 36
(8, 200000, 'DONE', '2024-04-17 12:30:00'), -- id: 37
(8, 150000, 'CANCEL', '2024-05-02 14:55:00'), -- id: 38
(8, 210000, 'PENDING', '2024-05-20 10:00:00'), -- id: 39
(9, 170000, 'PENDING', '2024-01-18 16:50:00'), -- id: 40
(9, 180000, 'PENDING', '2024-02-08 13:40:00'), -- id: 41
(9, 190000, 'DONE', '2024-03-14 11:30:00'), -- id: 42
(9, 160000, 'CANCEL', '2024-04-25 12:20:00'), -- id: 43
(9, 150000, 'PENDING', '2024-05-11 17:50:00'), -- id: 44
(10, 200000, 'DONE', '2024-01-12 14:30:00'), -- id: 45
(10, 170000, 'CANCEL', '2024-02-10 16:20:00'), -- id: 46
(10, 180000, 'PENDING', '2024-03-28 11:50:00'), -- id: 47
(10, 210000, 'DONE', '2024-04-06 10:10:00'), -- id: 48
(10, 160000, 'PENDING', '2024-05-16 09:30:00'), -- id: 49
(11, 190000, 'PENDING', '2024-01-27 14:40:00'), -- id: 50
(11, 220000, 'DONE', '2024-02-15 09:15:00'), -- id: 51
(11, 180000, 'CANCEL', '2024-03-30 12:00:00'), -- id: 52
(11, 170000, 'PENDING', '2024-04-18 11:00:00'), -- id: 53
(11, 150000, 'DONE', '2024-05-04 16:25:00'), -- id: 54
(12, 160000, 'PENDING', '2024-02-03 11:30:00'), -- id: 55
(12, 180000, 'DONE', '2024-03-14 14:10:00'), -- id: 56
(12, 210000, 'CANCEL', '2024-04-25 13:00:00'), -- id: 57
(12, 170000, 'PENDING', '2024-05-20 10:40:00'), -- id: 58
(12, 190000, 'DONE', '2024-05-27 17:10:00'), -- id: 59
(13, 150000, 'PENDING', '2024-01-10 12:00:00'), -- id: 60
(13, 180000, 'DONE', '2024-02-12 13:30:00'), -- id: 61
(13, 200000, 'CANCEL', '2024-03-04 16:00:00'), -- id: 62
(13, 170000, 'PENDING', '2024-04-11 11:30:00'), -- id: 63
(13, 160000, 'DONE', '2024-05-05 14:15:00'), -- id: 64
(14, 200000, 'PENDING', '2024-01-05 14:00:00'), -- id: 65
(14, 170000, 'DONE', '2024-02-18 11:30:00'), -- id: 66
(14, 180000, 'CANCEL', '2024-03-22 13:40:00'), -- id: 67
(14, 150000, 'PENDING', '2024-04-16 15:00:00'), -- id: 68
(14, 220000, 'DONE', '2024-05-05 17:25:00'), -- id: 69
(15, 190000, 'CANCEL', '2024-01-22 10:30:00'), -- id: 70
(15, 200000, 'PENDING', '2024-02-09 14:15:00'), -- id: 71
(15, 180000, 'DONE', '2024-03-03 11:10:00'), -- id: 72
(15, 160000, 'PENDING', '2024-04-19 16:40:00'), -- id: 73
(15, 220000, 'DONE', '2024-05-17 12:20:00'), -- id: 74
(16, 210000, 'PENDING', '2024-02-14 13:50:00'), -- id: 75
(16, 200000, 'CANCEL', '2024-03-10 15:30:00'), -- id: 76
(16, 170000, 'DONE', '2024-04-06 16:20:00'), -- id: 77
(16, 150000, 'PENDING', '2024-05-09 14:50:00'), -- id: 78
(16, 180000, 'DONE', '2024-05-24 10:30:00'), -- id: 79
(17, 160000, 'CANCEL', '2024-01-12 11:10:00'), -- id: 80
(17, 190000, 'PENDING', '2024-02-05 14:40:00'), -- id: 81
(17, 170000, 'DONE', '2024-03-18 13:25:00'), -- id: 82
(17, 200000, 'PENDING', '2024-04-14 12:55:00'), -- id: 83
(17, 180000, 'DONE', '2024-05-01 10:20:00'), -- id: 84
(18, 190000, 'PENDING', '2024-01-23 17:10:00'), -- id: 85
(18, 170000, 'DONE', '2024-02-16 12:00:00'), -- id: 86
(18, 220000, 'CANCEL', '2024-03-08 14:10:00'), -- id: 87
(18, 160000, 'PENDING', '2024-04-02 15:35:00'), -- id: 88
(18, 200000, 'DONE', '2024-05-14 13:15:00'), -- id: 89
(19, 210000, 'CANCEL', '2024-01-04 12:20:00'), -- id: 90
(19, 180000, 'PENDING', '2024-02-18 11:30:00'), -- id: 91
(19, 170000, 'DONE', '2024-03-02 14:50:00'), -- id: 92
(19, 190000, 'CANCEL', '2024-04-07 16:05:00'), -- id: 93
(19, 160000, 'PENDING', '2024-05-03 15:25:00'), -- id: 94
(20, 150000, 'PENDING', '2024-01-30 10:30:00'), -- id: 95
(20, 180000, 'DONE', '2024-02-28 13:50:00'), -- id: 96
(20, 200000, 'CANCEL', '2024-03-13 17:10:00'), -- id: 97
(20, 170000, 'PENDING', '2024-04-19 11:15:00'), -- id: 98
(20, 160000, 'DONE', '2024-05-21 12:00:00'), -- id: 99
(21, 190000, 'PENDING', '2024-01-18 11:10:00'), -- id: 100
(21, 210000, 'DONE', '2024-02-02 15:40:00'), -- id: 101
(21, 180000, 'CANCEL', '2024-03-25 10:15:00'), -- id: 102
(21, 160000, 'PENDING', '2024-04-10 14:30:00'), -- id: 103
(21, 200000, 'DONE', '2024-05-06 11:55:00'), -- id: 104
(22, 180000, 'CANCEL', '2024-02-09 10:10:00'), -- id: 105
(22, 150000, 'PENDING', '2024-03-04 17:25:00'), -- id: 106
(22, 160000, 'DONE', '2024-04-17 13:20:00'), -- id: 107
(22, 200000, 'CANCEL', '2024-05-23 09:50:00'), -- id: 108
(22, 170000, 'PENDING', '2024-05-30 14:35:00'), -- id: 109
(23, 160000, 'DONE', '2024-02-26 11:30:00'), -- id: 110
(23, 190000, 'PENDING', '2024-03-22 14:00:00'), -- id: 111
(23, 170000, 'CANCEL', '2024-04-08 13:40:00'), -- id: 112
(23, 200000, 'DONE', '2024-05-02 12:10:00'), -- id: 113
(23, 180000, 'PENDING', '2024-05-21 16:45:00'), -- id: 114
(24, 190000, 'PENDING', '2024-02-17 10:00:00'), -- id: 115
(24, 170000, 'DONE', '2024-03-05 12:15:00'), -- id: 116
(24, 220000, 'CANCEL', '2024-04-14 11:20:00'), -- id: 117
(24, 180000, 'PENDING', '2024-05-12 17:05:00'), -- id: 118
(24, 160000, 'DONE', '2024-05-28 13:25:00'), -- id: 119
(25, 200000, 'CANCEL', '2024-01-28 14:40:00'), -- id: 120
(25, 190000, 'PENDING', '2024-02-14 13:00:00'), -- id: 121
(25, 210000, 'DONE', '2024-03-01 15:50:00'), -- id: 122
(25, 170000, 'PENDING', '2024-04-09 12:05:00'), -- id: 123
(25, 180000, 'CANCEL', '2024-05-16 17:30:00'), -- id: 124
(26, 180000, 'PENDING', '2024-01-07 12:15:00'), -- id: 125
(26, 190000, 'DONE', '2024-02-12 14:40:00'), -- id: 126
(26, 200000, 'CANCEL', '2024-03-19 16:10:00'), -- id: 127
(26, 160000, 'PENDING', '2024-04-23 13:50:00'), -- id: 128
(26, 210000, 'DONE', '2024-05-10 11:30:00'), -- id: 129
(27, 170000, 'PENDING', '2024-01-20 15:00:00'), -- id: 130
(27, 200000, 'DONE', '2024-02-25 10:20:00'), -- id: 131
(27, 180000, 'CANCEL', '2024-03-15 11:45:00'), -- id: 132
(27, 190000, 'PENDING', '2024-04-01 16:30:00'), -- id: 133
(27, 160000, 'DONE', '2024-05-20 13:40:00'), -- id: 134
(28, 200000, 'CANCEL', '2024-02-19 17:10:00'), -- id: 135
(28, 180000, 'PENDING', '2024-03-09 14:25:00'), -- id: 136
(28, 190000, 'DONE', '2024-04-04 12:10:00'), -- id: 137
(28, 170000, 'CANCEL', '2024-05-11 15:55:00'), -- id: 138
(28, 160000, 'PENDING', '2024-05-25 10:30:00'), -- id: 139
(29, 210000, 'DONE', '2024-02-08 14:30:00'), -- id: 140
(29, 190000, 'PENDING', '2024-03-12 17:05:00'), -- id: 141
(29, 180000, 'CANCEL', '2024-04-13 11:20:00'), -- id: 142
(29, 200000, 'DONE', '2024-05-03 12:45:00'), -- id: 143
(29, 170000, 'PENDING', '2024-05-17 15:35:00'), -- id: 144
(30, 160000, 'PENDING', '2024-01-15 14:00:00'), -- id: 145
(30, 180000, 'DONE', '2024-02-22 12:10:00'), -- id: 146
(30, 170000, 'CANCEL', '2024-03-06 10:30:00'), -- id: 147
(30, 200000, 'PENDING', '2024-04-20 11:40:00'), -- id: 148
(30, 190000, 'DONE', '2024-05-14 17:25:00'), -- id: 149
(31, 180000, 'CANCEL', '2024-01-17 11:10:00'), -- id: 150
(31, 200000, 'PENDING', '2024-02-05 16:50:00'), -- id: 151
(31, 190000, 'DONE', '2024-03-03 13:20:00'), -- id: 152
(31, 170000, 'CANCEL', '2024-04-11 15:30:00'), -- id: 153
(31, 160000, 'PENDING', '2024-05-19 14:00:00'), -- id: 154
(32, 190000, 'DONE', '2024-01-26 12:50:00'), -- id: 155
(32, 210000, 'CANCEL', '2024-02-13 11:15:00'), -- id: 156
(32, 180000, 'PENDING', '2024-03-28 13:00:00'), -- id: 157
(32, 170000, 'DONE', '2024-04-30 15:20:00'), -- id: 158
(32, 160000, 'CANCEL', '2024-05-22 12:40:00'), -- id: 159
(33, 200000, 'PENDING', '2024-01-10 10:30:00'), -- id: 160
(33, 190000, 'DONE', '2024-02-27 17:00:00'), -- id: 161
(33, 180000, 'CANCEL', '2024-03-18 14:15:00'), -- id: 162
(33, 170000, 'PENDING', '2024-04-25 13:30:00'), -- id: 163
(33, 160000, 'DONE', '2024-05-08 11:25:00'), -- id: 164
(34, 190000, 'PENDING', '2024-01-12 15:30:00'), -- id: 165
(34, 170000, 'DONE', '2024-02-07 14:00:00'), -- id: 166
(34, 200000, 'CANCEL', '2024-03-21 16:10:00'), -- id: 167
(34, 180000, 'PENDING', '2024-04-06 13:20:00'), -- id: 168
(34, 160000, 'DONE', '2024-05-18 14:30:00'), -- id: 169
(35, 180000, 'CANCEL', '2024-01-11 12:10:00'), -- id: 170
(35, 170000, 'PENDING', '2024-02-18 17:35:00'), -- id: 171
(35, 190000, 'DONE', '2024-03-04 15:45:00'), -- id: 172
(35, 200000, 'PENDING', '2024-04-12 10:25:00'), -- id: 173
(35, 160000, 'CANCEL', '2024-05-29 16:55:00'), -- id: 174
(36, 200000, 'DONE', '2024-02-17 10:15:00'), -- id: 175
(36, 190000, 'PENDING', '2024-03-30 12:40:00'), -- id: 176
(36, 180000, 'CANCEL', '2024-04-14 14:50:00'), -- id: 177
(36, 170000, 'PENDING', '2024-05-06 15:30:00'), -- id: 178
(36, 160000, 'DONE', '2024-05-23 13:20:00'), -- id: 179
(37, 210000, 'CANCEL', '2024-02-12 16:25:00'), -- id: 180
(37, 200000, 'PENDING', '2024-03-22 11:10:00'), -- id: 181
(37, 190000, 'DONE', '2024-04-09 13:40:00'), -- id: 182
(37, 180000, 'CANCEL', '2024-05-13 17:00:00'), -- id: 183
(37, 170000, 'PENDING', '2024-05-25 14:55:00'), -- id: 184
(38, 160000, 'DONE', '2024-01-04 10:00:00'), -- id: 185
(38, 170000, 'PENDING', '2024-02-23 12:35:00'), -- id: 186
(38, 180000, 'CANCEL', '2024-03-12 16:50:00'), -- id: 187
(38, 200000, 'PENDING', '2024-04-28 11:00:00'), -- id: 188
(38, 190000, 'DONE', '2024-05-21 15:45:00'), -- id: 189
(39, 180000, 'PENDING', '2024-01-28 13:45:00'), -- id: 190
(39, 170000, 'DONE', '2024-02-03 14:15:00'), -- id: 191
(39, 190000, 'CANCEL', '2024-03-27 11:30:00'), -- id: 192
(39, 200000, 'PENDING', '2024-04-18 16:10:00'), -- id: 193
(39, 160000, 'DONE', '2024-05-02 10:25:00'), -- id: 194
(40, 210000, 'DONE', '2024-01-25 14:00:00'), -- id: 195
(40, 200000, 'PENDING', '2024-02-14 11:10:00'), -- id: 196
(40, 180000, 'CANCEL', '2024-03-10 17:25:00'), -- id: 197
(40, 190000, 'PENDING', '2024-04-05 16:40:00'), -- id: 198
(40, 170000, 'DONE', '2024-05-04 12:50:00'), -- id: 199
(41, 190000, 'DONE', '2024-02-04 16:15:00'), -- id: 200
(41, 180000, 'PENDING', '2024-03-17 12:30:00'), -- id: 201
(41, 200000, 'CANCEL', '2024-04-26 11:05:00'), -- id: 202
(41, 170000, 'DONE', '2024-05-18 14:20:00'), -- id: 203
(41, 160000, 'PENDING', '2024-05-29 13:00:00'), -- id: 204
(42, 170000, 'PENDING', '2024-01-21 15:40:00'), -- id: 205
(42, 180000, 'CANCEL', '2024-02-13 11:55:00'), -- id: 206
(42, 190000, 'DONE', '2024-03-24 13:25:00'), -- id: 207
(42, 160000, 'PENDING', '2024-04-22 10:40:00'), -- id: 208
(42, 200000, 'DONE', '2024-05-10 17:30:00'), -- id: 209
(43, 180000, 'CANCEL', '2024-02-08 17:05:00'), -- id: 210
(43, 170000, 'PENDING', '2024-03-02 11:25:00'), -- id: 211
(43, 160000, 'DONE', '2024-04-11 14:00:00'), -- id: 212
(43, 190000, 'CANCEL', '2024-05-14 15:40:00'), -- id: 213
(43, 200000, 'PENDING', '2024-05-22 16:25:00'), -- id: 214
(44, 170000, 'DONE', '2024-01-27 16:30:00'), -- id: 215
(44, 200000, 'PENDING', '2024-02-09 14:45:00'), -- id: 216
(44, 160000, 'CANCEL', '2024-03-13 13:10:00'), -- id: 217
(44, 190000, 'PENDING', '2024-04-08 12:20:00'), -- id: 218
(44, 180000, 'DONE', '2024-05-09 10:55:00'), -- id: 219
(45, 160000, 'PENDING', '2024-02-26 13:35:00'), -- id: 220
(45, 170000, 'DONE', '2024-03-05 10:50:00'), -- id: 221
(45, 200000, 'CANCEL', '2024-04-19 14:40:00'), -- id: 222
(45, 190000, 'PENDING', '2024-05-04 13:05:00'), -- id: 223
(45, 180000, 'DONE', '2024-05-23 16:10:00'), -- id: 224
(46, 170000, 'PENDING', '2024-02-14 15:20:00'), -- id: 225
(46, 160000, 'CANCEL', '2024-03-06 12:25:00'), -- id: 226
(46, 190000, 'PENDING', '2024-04-02 16:45:00'), -- id: 227
(46, 180000, 'DONE', '2024-05-01 13:35:00'), -- id: 228
(46, 200000, 'CANCEL', '2024-05-30 14:00:00'), -- id: 229
(47, 190000, 'PENDING', '2024-01-13 14:10:00'), -- id: 230
(47, 200000, 'DONE', '2024-02-01 17:00:00'), -- id: 231
(47, 170000, 'CANCEL', '2024-03-17 12:05:00'), -- id: 232
(47, 180000, 'PENDING', '2024-04-28 16:20:00'), -- id: 233
(47, 160000, 'DONE', '2024-05-08 10:50:00'), -- id: 234
(48, 200000, 'PENDING', '2024-01-30 13:50:00'), -- id: 235
(48, 170000, 'DONE', '2024-02-16 12:25:00'), -- id: 236
(48, 180000, 'CANCEL', '2024-03-09 10:15:00'), -- id: 237
(48, 190000, 'PENDING', '2024-04-04 15:30:00'), -- id: 238
(48, 160000, 'DONE', '2024-05-20 17:10:00'), -- id: 239
(49, 170000, 'PENDING', '2024-02-12 13:00:00'), -- id: 240
(49, 180000, 'DONE', '2024-03-30 17:15:00'), -- id: 241
(49, 200000, 'CANCEL', '2024-04-18 11:20:00'), -- id: 242
(49, 190000, 'PENDING', '2024-05-09 10:30:00'), -- id: 243
(49, 160000, 'DONE', '2024-05-22 14:45:00'), -- id: 244
(50, 190000, 'CANCEL', '2024-01-18 11:45:00'), -- id: 245
(50, 200000, 'PENDING', '2024-02-20 12:05:00'), -- id: 246
(50, 170000, 'DONE', '2024-03-12 16:30:00'), -- id: 247
(50, 160000, 'PENDING', '2024-04-14 13:50:00'), -- id: 248
(50, 180000, 'DONE', '2024-05-17 12:00:00'); -- id: 249

-- Bảng chi tiết hóa đơn
CREATE TABLE invoice_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES invoices(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    price BIGINT NOT NULL,
    discount_percentage INT NOT NULL,
    quantity INT NOT NULL,
    total_price BIGINT NOT NULL
);
INSERT INTO invoice_details(invoice_id, product_id, price, discount_percentage, quantity, total_price) VALUES
(1, 1, 100000, 10, 2, 180000), -- id: 1
(1, 5, 150000, 5, 1, 142500), -- id: 2
(1, 12, 120000, 15, 3, 306000), -- id: 3
(2, 3, 110000, 20, 1, 88000), -- id: 4
(2, 8, 130000, 10, 2, 234000), -- id: 5
(3, 11, 140000, 5, 1, 133000), -- id: 6
(3, 10, 125000, 10, 2, 225000), -- id: 7
(4, 4, 105000, 10, 2, 189000), -- id: 8
(4, 9, 135000, 5, 1, 128250), -- id: 9
(5, 6, 150000, 10, 2, 270000), -- id: 10
(5, 7, 160000, 15, 1, 136000), -- id: 11
(6, 2, 110000, 20, 2, 176000), -- id: 12
(6, 13, 125000, 5, 1, 118750), -- id: 13
(6, 14, 130000, 10, 2, 234000), -- id: 14
(7, 15, 120000, 5, 3, 342000), -- id: 15
(7, 16, 140000, 10, 1, 126000), -- id: 16
(8, 17, 135000, 5, 2, 257250), -- id: 17
(8, 18, 150000, 20, 1, 120000), -- id: 18
(8, 19, 125000, 10, 2, 225000), -- id: 19
(9, 20, 145000, 15, 1, 123250), -- id: 20
(9, 21, 160000, 5, 3, 456000), -- id: 21
(10, 22, 110000, 10, 2, 198000), -- id: 22
(10, 23, 120000, 15, 1, 102000), -- id: 23
(11, 24, 130000, 5, 3, 369000), -- id: 24
(11, 25, 140000, 20, 2, 224000), -- id: 25
(12, 26, 125000, 10, 1, 112500), -- id: 26
(12, 27, 150000, 15, 2, 255000), -- id: 27
(12, 28, 135000, 5, 3, 382500), -- id: 28
(13, 29, 140000, 20, 1, 112000), -- id: 29
(13, 30, 160000, 10, 2, 288000), -- id: 30
(13, 31, 125000, 5, 3, 356250), -- id: 31
(14, 32, 120000, 10, 1, 108000), -- id: 32
(14, 33, 150000, 20, 2, 240000), -- id: 33
(14, 34, 130000, 15, 2, 221000), -- id: 34
(15, 35, 110000, 10, 2, 198000), -- id: 35
(15, 36, 120000, 20, 1, 96000), -- id: 36
(16, 37, 130000, 5, 1, 123500), -- id: 37
(16, 38, 140000, 10, 2, 252000), -- id: 38
(17, 39, 125000, 10, 3, 337500), -- id: 39
(17, 40, 150000, 5, 1, 142500), -- id: 40
(18, 41, 160000, 15, 2, 272000), -- id: 41
(18, 42, 110000, 10, 1, 99000), -- id: 42
(19, 43, 135000, 5, 3, 385500), -- id: 43
(19, 44, 150000, 20, 2, 240000), -- id: 44
(20, 45, 120000, 10, 1, 108000), -- id: 45
(20, 46, 130000, 15, 2, 221000), -- id: 46
(21, 47, 110000, 5, 3, 319500), -- id: 47
(21, 48, 140000, 10, 1, 126000), -- id: 48
(22, 49, 125000, 20, 2, 200000), -- id: 49
(22, 50, 150000, 10, 3, 405000), -- id: 50
(23, 51, 160000, 5, 2, 304000), -- id: 51
(23, 52, 120000, 10, 1, 108000), -- id: 52
(24, 53, 130000, 20, 1, 104000), -- id: 53
(24, 54, 140000, 5, 2, 266000), -- id: 54
(25, 55, 125000, 15, 1, 106250), -- id: 55
(25, 56, 150000, 10, 3, 405000), -- id: 56
(26, 57, 110000, 10, 2, 198000), -- id: 57
(26, 58, 160000, 20, 1, 128000), -- id: 58
(27, 59, 130000, 10, 1, 117000), -- id: 59
(27, 60, 140000, 5, 2, 266000), -- id: 60
(28, 61, 125000, 10, 2, 225000), -- id: 61
(28, 62, 150000, 15, 3, 382500), -- id: 62
(29, 63, 110000, 20, 1, 88000), -- id: 63
(29, 64, 120000, 5, 3, 342000), -- id: 64
(30, 25, 135000, 0, 1, 135000), -- id: 65
(30, 37, 125000, 5, 3, 356250), -- id: 66
(30, 61, 130000, 5, 2, 247000), -- id: 67
(30, 30, 150000, 20, 3, 360000), -- id: 68
(30, 40, 140000, 5, 2, 266000), -- id: 69
(30, 41, 125000, 20, 1, 100000), -- id: 70
(31, 12, 130000, 10, 2, 234000), -- id: 71
(31, 43, 140000, 15, 1, 119000), -- id: 72
(31, 21, 150000, 0, 1, 150000), -- id: 73
(31, 7, 120000, 20, 2, 192000), -- id: 74
(32, 18, 125000, 5, 3, 356250), -- id: 75
(32, 38, 145000, 10, 1, 130500), -- id: 76
(32, 9, 135000, 15, 1, 114750), -- id: 77
(32, 57, 155000, 5, 2, 294500), -- id: 78
(33, 6, 100000, 20, 3, 240000), -- id: 79
(33, 44, 140000, 10, 1, 126000), -- id: 80
(33, 59, 160000, 0, 1, 160000), -- id: 81
(33, 2, 110000, 5, 2, 209000), -- id: 82
(34, 3, 120000, 10, 1, 108000), -- id: 83
(34, 26, 140000, 15, 2, 238000), -- id: 84
(34, 64, 130000, 5, 1, 123500), -- id: 85
(34, 11, 150000, 0, 2, 300000), -- id: 86
(35, 25, 145000, 20, 1, 116000), -- id: 87
(35, 40, 135000, 5, 1, 128250), -- id: 88
(35, 1, 120000, 10, 3, 324000), -- id: 89
(35, 15, 110000, 0, 2, 220000), -- id: 90
(36, 19, 150000, 5, 1, 142500), -- id: 91
(36, 27, 130000, 10, 2, 234000), -- id: 92
(36, 32, 100000, 15, 3, 255000), -- id: 93
(36, 5, 125000, 5, 1, 118750), -- id: 94
(37, 60, 160000, 20, 1, 128000), -- id: 95
(37, 23, 145000, 0, 2, 290000), -- id: 96
(37, 36, 120000, 5, 1, 114000), -- id: 97
(37, 17, 130000, 10, 2, 234000), -- id: 98
(38, 30, 135000, 5, 1, 128250), -- id: 99
(38, 31, 140000, 15, 2, 238000), -- id: 100
(38, 4, 125000, 10, 1, 112500), -- id: 101
(38, 20, 150000, 0, 3, 450000), -- id: 102
(39, 16, 140000, 10, 2, 252000), -- id: 103
(39, 28, 130000, 0, 1, 130000), -- id: 104
(39, 33, 125000, 5, 1, 118750), -- id: 105
(39, 54, 150000, 20, 1, 120000), -- id: 106
(40, 41, 135000, 10, 2, 243000), -- id: 107
(40, 60, 120000, 5, 1, 114000), -- id: 108
(40, 17, 145000, 15, 3, 369375), -- id: 109
(40, 13, 110000, 0, 1, 110000), -- id: 110
(41, 22, 130000, 20, 2, 208000), -- id: 111
(41, 47, 125000, 10, 1, 112500), -- id: 112
(41, 30, 140000, 5, 3, 399000), -- id: 113
(41, 7, 100000, 0, 2, 200000), -- id: 114
(42, 58, 150000, 20, 1, 120000), -- id: 115
(42, 14, 145000, 10, 2, 261000), -- id: 116
(42, 5, 135000, 15, 1, 114750), -- id: 117
(42, 35, 120000, 5, 1, 114000), -- id: 118
(43, 36, 130000, 10, 3, 351000), -- id: 119
(43, 44, 110000, 0, 2, 220000), -- id: 120
(43, 26, 125000, 5, 1, 118750), -- id: 121
(43, 8, 150000, 20, 1, 120000), -- id: 122
(44, 49, 135000, 15, 1, 114750), -- id: 123
(44, 2, 140000, 10, 2, 252000), -- id: 124
(44, 21, 120000, 5, 1, 114000), -- id: 125
(44, 10, 110000, 0, 1, 110000), -- id: 126
(45, 3, 130000, 10, 2, 234000), -- id: 127
(45, 42, 150000, 5, 1, 142500), -- id: 128
(45, 31, 125000, 20, 1, 100000), -- id: 129
(45, 6, 145000, 15, 2, 246500), -- id: 130
(46, 20, 100000, 10, 2, 180000), -- id: 131
(46, 18, 140000, 5, 3, 399000), -- id: 132
(46, 53, 135000, 10, 1, 121500), -- id: 133
(46, 11, 150000, 15, 1, 127500), -- id: 134
(47, 34, 125000, 5, 2, 237500), -- id: 135
(47, 46, 130000, 0, 1, 130000), -- id: 136
(47, 50, 145000, 10, 1, 130500), -- id: 137
(47, 27, 120000, 5, 1, 114000), -- id: 138
(48, 40, 150000, 20, 2, 240000), -- id: 139
(48, 12, 135000, 5, 3, 384750), -- id: 140
(48, 16, 110000, 0, 1, 110000), -- id: 141
(48, 9, 125000, 10, 2, 225000), -- id: 142
(49, 1, 140000, 15, 1, 119000), -- id: 143
(49, 23, 130000, 5, 3, 370500), -- id: 144
(49, 15, 145000, 10, 1, 130500), -- id: 145
(49, 24, 120000, 5, 2, 228000), -- id: 146
(50, 48, 150000, 0, 1, 150000), -- id: 147
(50, 55, 135000, 10, 2, 243000), -- id: 148
(50, 59, 125000, 15, 1, 106250), -- id: 149
(50, 19, 140000, 5, 2, 266000), -- id: 150
(50, 32, 100000, 10, 1, 90000), -- id: 151
(50, 13, 110000, 0, 1, 110000), -- id: 152
(51, 22, 130000, 5, 2, 247000), -- id: 153
(51, 35, 145000, 10, 1, 130500), -- id: 154
(51, 44, 150000, 20, 1, 120000), -- id: 155
(51, 17, 120000, 0, 1, 120000), -- id: 156
(52, 28, 140000, 15, 1, 119000), -- id: 157
(52, 50, 125000, 5, 2, 237500), -- id: 158
(52, 6, 110000, 10, 1, 99000), -- id: 159
(52, 60, 130000, 5, 1, 123500), -- id: 160
(52, 3, 145000, 0, 1, 145000), -- id: 161
(53, 38, 150000, 20, 2, 240000), -- id: 162
(53, 33, 135000, 5, 2, 256500), -- id: 163
(53, 19, 125000, 0, 1, 125000), -- id: 164
(53, 10, 140000, 15, 1, 119000), -- id: 165
(54, 46, 130000, 5, 1, 123500), -- id: 166
(54, 12, 100000, 0, 2, 200000), -- id: 167
(54, 8, 145000, 10, 2, 261000), -- id: 168
(54, 26, 120000, 5, 1, 114000), -- id: 169
(55, 49, 135000, 5, 2, 256500), -- id: 170
(55, 15, 110000, 0, 1, 110000), -- id: 171
(55, 41, 130000, 15, 1, 110500), -- id: 172
(55, 13, 150000, 20, 1, 120000), -- id: 173
(55, 2, 140000, 10, 1, 126000), -- id: 174
(56, 5, 120000, 0, 2, 240000), -- id: 175
(56, 32, 145000, 20, 1, 116000), -- id: 176
(56, 36, 125000, 15, 2, 212500), -- id: 177
(56, 58, 150000, 10, 1, 135000), -- id: 178
(57, 24, 140000, 5, 2, 266000), -- id: 179
(57, 21, 135000, 0, 1, 135000), -- id: 180
(57, 37, 130000, 10, 3, 351000), -- id: 181
(57, 59, 125000, 5, 1, 118750), -- id: 182
(58, 7, 100000, 0, 1, 100000), -- id: 183
(58, 18, 110000, 5, 2, 209000), -- id: 184
(58, 30, 145000, 10, 2, 261000), -- id: 185
(58, 4, 135000, 20, 1, 108000), -- id: 186
(59, 42, 130000, 15, 3, 331500), -- id: 187
(59, 34, 120000, 0, 1, 120000), -- id: 188
(59, 9, 140000, 10, 1, 126000), -- id: 189
(59, 20, 125000, 5, 2, 237500), -- id: 190
(60, 27, 150000, 5, 1, 142500), -- id: 191
(60, 1, 145000, 15, 1, 123250), -- id: 192
(60, 14, 130000, 10, 2, 234000), -- id: 193
(60, 39, 140000, 20, 1, 112000), -- id: 194
(60, 52, 135000, 5, 1, 128250), -- id: 195
(60, 25, 125000, 0, 1, 125000), -- id: 196
(60, 43, 100000, 10, 1, 90000), -- id: 197
(60, 31, 115000, 5, 1, 109250), -- id: 198
(60, 11, 120000, 15, 1, 102000), -- id: 199
(60, 57, 150000, 10, 1, 135000), -- id: 200
(60, 45, 140000, 0, 1, 140000), -- id: 201
(60, 56, 130000, 5, 1, 123500), -- id: 202
(61, 44, 135000, 5, 2, 257250), -- id: 203
(61, 22, 125000, 15, 1, 106250), -- id: 204
(61, 34, 140000, 10, 1, 126000), -- id: 205
(61, 7, 150000, 0, 2, 300000), -- id: 206
(61, 20, 130000, 5, 1, 123500), -- id: 207
(62, 33, 110000, 10, 1, 99000), -- id: 208
(62, 4, 125000, 0, 2, 250000), -- id: 209
(62, 53, 140000, 20, 1, 112000), -- id: 210
(62, 8, 135000, 5, 3, 384750), -- id: 211
(62, 5, 120000, 15, 1, 102000), -- id: 212
(63, 19, 150000, 10, 1, 135000), -- id: 213
(63, 11, 130000, 5, 2, 246000), -- id: 214
(63, 50, 125000, 0, 1, 125000), -- id: 215
(63, 38, 140000, 20, 1, 112000), -- id: 216
(64, 18, 145000, 5, 2, 261500), -- id: 217
(64, 16, 120000, 0, 2, 240000), -- id: 218
(64, 21, 130000, 15, 1, 110500), -- id: 219
(64, 9, 135000, 10, 1, 121500), -- id: 220
(64, 1, 125000, 0, 2, 250000), -- id: 221
(65, 42, 130000, 5, 2, 247000), -- id: 222
(65, 31, 140000, 10, 1, 126000), -- id: 223
(65, 24, 120000, 20, 1, 96000), -- id: 224
(65, 28, 135000, 5, 1, 128250), -- id: 225
(66, 47, 145000, 15, 1, 123250), -- id: 226
(66, 14, 100000, 0, 2, 200000), -- id: 227
(66, 8, 125000, 5, 2, 237500), -- id: 228
(66, 33, 150000, 10, 1, 135000), -- id: 229
(66, 26, 120000, 20, 1, 96000), -- id: 230
(67, 45, 130000, 5, 1, 123500), -- id: 231
(67, 21, 135000, 10, 2, 243000), -- id: 232
(67, 35, 120000, 15, 1, 102000), -- id: 233
(67, 19, 145000, 0, 1, 145000), -- id: 234
(68, 2, 150000, 5, 2, 285000), -- id: 235
(68, 41, 130000, 10, 3, 351000), -- id: 236
(68, 43, 120000, 0, 1, 120000), -- id: 237
(68, 51, 125000, 15, 1, 106250), -- id: 238
(68, 40, 135000, 5, 2, 256500), -- id: 239
(69, 48, 130000, 10, 1, 117000), -- id: 240
(69, 59, 125000, 20, 1, 100000), -- id: 241
(69, 6, 150000, 5, 1, 142500), -- id: 242
(69, 52, 140000, 0, 1, 140000), -- id: 243
(70, 7, 130000, 10, 2, 234000), -- id: 244
(70, 54, 120000, 0, 2, 240000), -- id: 245
(70, 43, 145000, 5, 1, 137750), -- id: 246
(70, 12, 110000, 15, 3, 283500), -- id: 247
(71, 16, 135000, 10, 2, 243000), -- id: 248
(71, 33, 150000, 5, 1, 142500), -- id: 249
(71, 58, 125000, 0, 1, 125000), -- id: 250
(71, 28, 130000, 20, 1, 104000), -- id: 251
(72, 39, 140000, 5, 2, 266000), -- id: 252
(72, 23, 120000, 15, 1, 102000), -- id: 253
(72, 11, 135000, 5, 2, 257250), -- id: 254
(72, 5, 145000, 10, 1, 130500), -- id: 255
(72, 27, 150000, 0, 2, 300000), -- id: 256
(73, 31, 130000, 10, 1, 117000), -- id: 257
(73, 33, 125000, 5, 1, 118750), -- id: 258
(73, 29, 140000, 5, 3, 399000), -- id: 259
(73, 53, 100000, 0, 1, 100000), -- id: 260
(74, 44, 130000, 15, 2, 221000), -- id: 261
(74, 49, 120000, 10, 1, 108000), -- id: 262
(74, 22, 150000, 5, 2, 285000), -- id: 263
(74, 19, 135000, 0, 1, 135000), -- id: 264
(75, 42, 125000, 20, 2, 200000), -- id: 265
(75, 37, 145000, 5, 1, 137750), -- id: 266
(75, 24, 130000, 10, 3, 351000), -- id: 267
(75, 15, 100000, 0, 1, 100000), -- id: 268
(76, 48, 140000, 10, 1, 126000), -- id: 269
(76, 13, 130000, 5, 2, 246000), -- id: 270
(76, 52, 125000, 0, 1, 125000), -- id: 271
(76, 50, 145000, 15, 1, 123250), -- id: 272
(77, 17, 150000, 5, 1, 142500), -- id: 273
(77, 53, 120000, 10, 2, 216000), -- id: 274
(77, 36, 130000, 15, 1, 110500), -- id: 275
(77, 25, 140000, 0, 2, 280000), -- id: 276
(78, 39, 125000, 20, 1, 100000), -- id: 277
(78, 8, 135000, 5, 2, 257250), -- id: 278
(78, 18, 150000, 0, 1, 150000), -- id: 279
(78, 30, 120000, 10, 3, 324000), -- id: 280
(79, 51, 145000, 5, 2, 274500), -- id: 281
(79, 33, 135000, 10, 1, 121500), -- id: 282
(79, 7, 130000, 15, 2, 221000), -- id: 283
(79, 43, 125000, 0, 1, 125000), -- id: 284
(80, 19, 150000, 5, 1, 142500), -- id: 285
(80, 29, 140000, 10, 2, 252000), -- id: 286
(80, 46, 120000, 5, 3, 342000), -- id: 287
(80, 12, 130000, 0, 1, 130000), -- id: 288
(81, 34, 125000, 20, 1, 100000), -- id: 289
(81, 42, 135000, 5, 2, 257250), -- id: 290
(81, 26, 140000, 10, 1, 126000), -- id: 291
(81, 21, 150000, 15, 2, 255000), -- id: 292
(82, 49, 120000, 0, 1, 120000), -- id: 293
(82, 40, 125000, 5, 1, 118750), -- id: 294
(82, 28, 130000, 15, 1, 110500), -- id: 295
(82, 53, 135000, 0, 1, 135000), -- id: 296
(83, 24, 145000, 20, 1, 116000), -- id: 297
(83, 32, 120000, 10, 1, 108000), -- id: 298
(83, 41, 130000, 5, 2, 246000), -- id: 299
(83, 4, 140000, 0, 1, 140000), -- id: 300
(84, 43, 150000, 15, 1, 127500), -- id: 301
(84, 19, 120000, 5, 1, 114000), -- id: 302
(85, 17, 130000, 10, 1, 117000), -- id: 303
(85, 12, 140000, 5, 2, 266000), -- id: 304
(85, 56, 120000, 15, 1, 102000), -- id: 305
(85, 8, 150000, 0, 2, 300000), -- id: 306
(86, 35, 125000, 10, 3, 337500), -- id: 307
(86, 53, 130000, 5, 1, 123500), -- id: 308
(86, 48, 135000, 0, 2, 270000), -- id: 309
(86, 23, 140000, 20, 1, 112000), -- id: 310
(87, 42, 150000, 5, 1, 142500), -- id: 311
(87, 33, 120000, 10, 2, 216000), -- id: 312
(87, 29, 130000, 15, 2, 221000), -- id: 313
(87, 6, 145000, 0, 1, 145000), -- id: 314
(88, 18, 125000, 5, 3, 356250), -- id: 315
(88, 22, 130000, 10, 1, 117000), -- id: 316
(88, 41, 140000, 5, 1, 133000), -- id: 317
(88, 27, 150000, 0, 2, 300000), -- id: 318
(89, 56, 120000, 10, 1, 108000), -- id: 319
(89, 48, 125000, 5, 2, 237500), -- id: 320
(89, 13, 130000, 0, 3, 390000), -- id: 321
(89, 31, 140000, 20, 1, 112000), -- id: 322
(90, 5, 135000, 5, 2, 257250), -- id: 323
(90, 47, 150000, 10, 1, 135000), -- id: 324
(90, 44, 120000, 0, 1, 120000), -- id: 325
(90, 36, 125000, 15, 3, 318750), -- id: 326
(91, 14, 130000, 5, 2, 246000), -- id: 327
(91, 50, 135000, 10, 1, 121500), -- id: 328
(91, 12, 140000, 0, 2, 280000), -- id: 329
(91, 29, 120000, 5, 3, 342000), -- id: 330
(92, 3, 125000, 10, 2, 225000), -- id: 331
(92, 41, 150000, 5, 1, 142500), -- id: 332
(92, 30, 130000, 0, 2, 260000), -- id: 333
(92, 24, 135000, 20, 1, 108000), -- id: 334
(93, 23, 120000, 15, 3, 306000), -- id: 335
(93, 13, 130000, 5, 1, 123500), -- id: 336
(93, 19, 140000, 10, 2, 252000), -- id: 337
(93, 10, 150000, 0, 2, 300000), -- id: 338
(94, 25, 135000, 0, 1, 135000), -- id: 339
(94, 17, 125000, 5, 3, 356250), -- id: 340
(94, 28, 120000, 10, 2, 216000), -- id: 341
(94, 5, 130000, 15, 1, 110500), -- id: 342
(95, 45, 140000, 0, 1, 140000), -- id: 343
(95, 22, 150000, 5, 1, 142500), -- id: 344
(95, 33, 125000, 20, 1, 100000), -- id: 345
(95, 9, 135000, 10, 2, 243000), -- id: 346
(96, 52, 120000, 15, 3, 306000), -- id: 347
(96, 16, 130000, 0, 2, 260000), -- id: 348
(96, 26, 140000, 10, 1, 126000), -- id: 349
(96, 41, 150000, 5, 1, 142500), -- id: 350
(97, 29, 135000, 5, 3, 385500), -- id: 351
(97, 18, 125000, 10, 2, 225000), -- id: 352
(98, 44, 130000, 15, 2, 221000), -- id: 353
(98, 12, 140000, 10, 3, 378000), -- id: 354
(98, 33, 120000, 5, 1, 114000), -- id: 355
(98, 23, 125000, 20, 1, 100000), -- id: 356
(99, 28, 135000, 5, 2, 257250), -- id: 357
(99, 19, 140000, 10, 1, 126000), -- id: 358
(99, 45, 120000, 0, 2, 240000), -- id: 359
(99, 8, 150000, 5, 3, 427500), -- id: 360
(100, 24, 125000, 10, 2, 225000), -- id: 361
(100, 5, 130000, 15, 1, 110500), -- id: 362
(100, 47, 140000, 5, 2, 266000), -- id: 363
(100, 21, 120000, 0, 1, 120000), -- id: 364
(101, 22, 135000, 0, 2, 270000), -- id: 365
(101, 53, 130000, 10, 1, 117000), -- id: 366
(101, 16, 140000, 15, 3, 357000), -- id: 367
(101, 33, 120000, 5, 1, 114000), -- id: 368
(102, 14, 150000, 0, 1, 150000), -- id: 369
(102, 12, 125000, 5, 3, 356250), -- id: 370
(102, 48, 130000, 10, 2, 234000), -- id: 371
(102, 8, 135000, 0, 1, 135000), -- id: 372
(103, 49, 120000, 10, 1, 108000), -- id: 373
(103, 13, 140000, 20, 2, 224000), -- id: 374
(103, 18, 125000, 5, 1, 118750), -- id: 375
(103, 5, 150000, 15, 1, 127500), -- id: 376
(104, 41, 135000, 0, 3, 405000), -- id: 377
(104, 10, 130000, 10, 2, 234000), -- id: 378
(104, 44, 120000, 5, 1, 114000), -- id: 379
(104, 29, 140000, 15, 1, 119000), -- id: 380
(105, 30, 150000, 5, 2, 285000), -- id: 381
(105, 11, 125000, 0, 3, 375000), -- id: 382
(105, 53, 130000, 20, 2, 208000), -- id: 383
(105, 6, 140000, 10, 1, 126000), -- id: 384
(106, 19, 120000, 5, 1, 114000), -- id: 385
(106, 13, 135000, 0, 3, 405000), -- id: 386
(106, 52, 125000, 10, 1, 112500), -- id: 387
(106, 42, 150000, 15, 1, 127500), -- id: 388
(107, 40, 130000, 20, 2, 208000), -- id: 389
(107, 44, 140000, 5, 1, 133000), -- id: 390
(107, 22, 120000, 10, 1, 108000), -- id: 391
(107, 17, 125000, 0, 3, 375000), -- id: 392
(108, 32, 135000, 5, 2, 257250), -- id: 393
(108, 24, 150000, 15, 1, 127500), -- id: 394
(108, 50, 130000, 10, 2, 234000), -- id: 395
(108, 41, 120000, 0, 1, 120000), -- id: 396
(109, 19, 125000, 10, 1, 112500), -- id: 397
(109, 48, 130000, 15, 2, 221000), -- id: 398
(109, 35, 140000, 5, 3, 399000), -- id: 399
(109, 9, 120000, 0, 1, 120000), -- id: 400
(110, 17, 135000, 5, 1, 128250), -- id: 401
(110, 23, 150000, 10, 1, 135000), -- id: 402
(111, 42, 120000, 15, 3, 306000), -- id: 403
(111, 13, 135000, 5, 2, 257250), -- id: 404
(111, 48, 130000, 0, 1, 130000), -- id: 405
(111, 56, 150000, 10, 2, 270000), -- id: 406
(112, 29, 125000, 10, 3, 337500), -- id: 407
(112, 33, 140000, 20, 1, 112000), -- id: 408
(112, 8, 120000, 5, 1, 114000), -- id: 409
(112, 44, 130000, 0, 2, 260000), -- id: 410
(113, 31, 135000, 10, 2, 243000), -- id: 411
(113, 50, 140000, 15, 1, 119000), -- id: 412
(113, 5, 120000, 5, 1, 114000), -- id: 413
(113, 26, 150000, 0, 3, 450000), -- id: 414
(114, 44, 130000, 20, 2, 208000), -- id: 415
(114, 22, 120000, 5, 3, 342000), -- id: 416
(114, 10, 135000, 0, 1, 135000), -- id: 417
(114, 9, 150000, 10, 2, 270000), -- id: 418
(115, 36, 120000, 15, 2, 204000), -- id: 419
(115, 13, 130000, 0, 1, 130000), -- id: 420
(115, 18, 140000, 10, 1, 126000), -- id: 421
(115, 31, 150000, 5, 2, 285000), -- id: 422
(116, 25, 135000, 5, 2, 257250), -- id: 423
(116, 16, 125000, 10, 3, 337500), -- id: 424
(116, 6, 130000, 0, 2, 260000), -- id: 425
(116, 45, 140000, 5, 1, 133000), -- id: 426
(117, 8, 120000, 0, 1, 120000), -- id: 427
(117, 49, 130000, 15, 2, 221000), -- id: 428
(117, 23, 135000, 10, 3, 405000), -- id: 429
(117, 9, 150000, 5, 1, 142500), -- id: 430
(118, 30, 125000, 20, 1, 100000), -- id: 431
(118, 47, 140000, 10, 1, 126000), -- id: 432
(118, 19, 120000, 5, 3, 342000), -- id: 433
(118, 13, 130000, 0, 2, 260000), -- id: 434
(119, 12, 135000, 0, 1, 135000), -- id: 435
(119, 48, 140000, 5, 2, 266000), -- id: 436
(119, 11, 150000, 10, 3, 405000), -- id: 437
(119, 41, 120000, 15, 1, 102000), -- id: 438
(120, 44, 130000, 10, 2, 234000), -- id: 439
(120, 19, 140000, 5, 1, 133000), -- id: 440
(120, 17, 120000, 15, 3, 306000), -- id: 441
(120, 31, 150000, 0, 2, 300000), -- id: 442
(121, 42, 125000, 10, 1, 112500), -- id: 443
(121, 33, 130000, 5, 2, 246000), -- id: 444
(121, 5, 135000, 0, 3, 405000), -- id: 445
(121, 8, 140000, 10, 1, 126000), -- id: 446
(122, 12, 120000, 5, 2, 228000), -- id: 447
(122, 46, 150000, 20, 1, 120000), -- id: 448
(122, 53, 130000, 0, 1, 130000), -- id: 449
(122, 29, 135000, 15, 1, 114750), -- id: 450
(123, 14, 140000, 5, 1, 133000), -- id: 451
(123, 7, 120000, 0, 2, 240000), -- id: 452
(123, 33, 130000, 10, 3, 351000), -- id: 453
(123, 45, 135000, 15, 1, 114750), -- id: 454
(124, 40, 150000, 10, 2, 270000), -- id: 455
(124, 12, 125000, 5, 3, 356250), -- id: 456
(124, 53, 130000, 0, 1, 130000), -- id: 457
(124, 17, 120000, 15, 2, 204000), -- id: 458
(125, 18, 140000, 10, 1, 126000), -- id: 459
(125, 5, 130000, 0, 3, 390000), -- id: 460
(125, 33, 135000, 5, 2, 257250), -- id: 461
(125, 7, 120000, 20, 3, 288000), -- id: 462
(126, 50, 150000, 5, 2, 285000), -- id: 463
(126, 9, 140000, 0, 1, 140000), -- id: 464
(126, 44, 130000, 15, 3, 331500), -- id: 465
(126, 6, 120000, 10, 2, 216000), -- id: 466
(127, 19, 135000, 5, 1, 128250), -- id: 467
(127, 42, 150000, 0, 2, 300000), -- id: 468
(127, 27, 130000, 10, 1, 117000), -- id: 469
(127, 5, 120000, 5, 2, 228000), -- id: 470
(128, 33, 140000, 20, 2, 224000), -- id: 471
(128, 29, 135000, 0, 1, 135000), -- id: 472
(128, 7, 120000, 10, 2, 216000), -- id: 473
(128, 18, 150000, 5, 3, 427500), -- id: 474
(129, 9, 130000, 15, 1, 110500), -- id: 475
(129, 40, 140000, 0, 2, 280000), -- id: 476
(129, 12, 125000, 20, 2, 200000), -- id: 477
(129, 33, 120000, 5, 3, 342000), -- id: 478
(130, 13, 135000, 0, 3, 405000), -- id: 479
(130, 24, 150000, 10, 2, 270000), -- id: 480
(130, 27, 130000, 5, 1, 123500), -- id: 481
(130, 19, 120000, 0, 1, 120000), -- id: 482
(131, 22, 140000, 15, 3, 357000), -- id: 483
(131, 44, 130000, 10, 2, 234000), -- id: 484
(131, 31, 135000, 5, 2, 257250), -- id: 485
(131, 33, 120000, 0, 1, 120000), -- id: 486
(132, 19, 125000, 10, 1, 112500), -- id: 487
(132, 9, 140000, 5, 2, 266000), -- id: 488
(132, 45, 150000, 0, 1, 150000), -- id: 489
(132, 7, 130000, 15, 3, 331500), -- id: 490
(133, 6, 120000, 20, 2, 192000), -- id: 491
(133, 26, 135000, 10, 1, 121500), -- id: 492
(133, 17, 140000, 5, 2, 266000), -- id: 493
(133, 44, 130000, 0, 1, 130000), -- id: 494
(134, 5, 120000, 15, 3, 306000), -- id: 495
(134, 47, 150000, 10, 2, 270000), -- id: 496
(134, 28, 130000, 0, 3, 390000), -- id: 497
(134, 6, 135000, 5, 1, 128250), -- id: 498
(135, 44, 120000, 20, 1, 96000), -- id: 499
(135, 24, 130000, 10, 3, 351000), -- id: 500
(136, 12, 120000, 5, 2, 228000), -- id: 501
(136, 53, 130000, 10, 3, 351000), -- id: 502
(136, 9, 135000, 0, 1, 135000), -- id: 503
(136, 7, 140000, 5, 1, 133000), -- id: 504
(137, 26, 125000, 15, 2, 212500), -- id: 505
(137, 16, 120000, 10, 1, 108000), -- id: 506
(137, 30, 150000, 0, 2, 300000), -- id: 507
(137, 45, 135000, 5, 3, 385500), -- id: 508
(138, 41, 140000, 10, 2, 252000), -- id: 509
(138, 39, 130000, 20, 1, 104000), -- id: 510
(138, 8, 120000, 0, 3, 360000), -- id: 511
(138, 11, 135000, 5, 1, 128250), -- id: 512
(139, 33, 125000, 10, 1, 112500), -- id: 513
(139, 42, 140000, 15, 2, 238000), -- id: 514
(139, 50, 130000, 0, 3, 390000), -- id: 515
(139, 10, 150000, 10, 1, 135000), -- id: 516
(140, 12, 120000, 5, 2, 228000), -- id: 517
(140, 13, 130000, 10, 3, 351000), -- id: 518
(140, 7, 135000, 0, 2, 270000), -- id: 519
(140, 44, 150000, 5, 1, 142500), -- id: 520
(141, 22, 120000, 0, 1, 120000), -- id: 521
(141, 18, 130000, 10, 2, 234000), -- id: 522
(141, 9, 135000, 5, 3, 386250), -- id: 523
(141, 6, 140000, 15, 1, 119000), -- id: 524
(142, 25, 150000, 20, 1, 120000), -- id: 525
(142, 37, 120000, 5, 2, 228000), -- id: 526
(142, 53, 130000, 10, 3, 351000), -- id: 527
(142, 7, 135000, 0, 1, 135000), -- id: 528
(143, 44, 140000, 15, 2, 238000), -- id: 529
(143, 8, 125000, 5, 1, 118750), -- id: 530
(143, 31, 130000, 10, 3, 351000), -- id: 531
(143, 50, 120000, 0, 2, 240000), -- id: 532
(144, 33, 135000, 5, 1, 128250), -- id: 533
(144, 22, 120000, 0, 2, 240000), -- id: 534
(144, 39, 140000, 10, 1, 126000), -- id: 535
(144, 13, 130000, 5, 3, 369750), -- id: 536
(145, 7, 120000, 5, 2, 228000), -- id: 537
(145, 44, 130000, 10, 1, 117000), -- id: 538
(145, 53, 150000, 20, 1, 120000), -- id: 539
(145, 31, 135000, 0, 2, 270000), -- id: 540
(146, 5, 140000, 5, 2, 266000), -- id: 541
(146, 33, 120000, 15, 3, 306000), -- id: 542
(146, 12, 130000, 0, 1, 130000), -- id: 543
(146, 22, 135000, 10, 2, 243000), -- id: 544
(147, 41, 120000, 10, 3, 324000), -- id: 545
(147, 44, 130000, 5, 2, 246000), -- id: 546
(147, 33, 140000, 0, 1, 140000), -- id: 547
(147, 6, 150000, 10, 1, 135000), -- id: 548
(148, 45, 120000, 5, 3, 342000), -- id: 549
(148, 5, 130000, 0, 2, 260000), -- id: 550
(149, 17, 135000, 5, 1, 128250), -- id: 551
(149, 30, 120000, 10, 2, 216000), -- id: 552
(149, 40, 150000, 15, 3, 382500), -- id: 553
(149, 22, 130000, 0, 1, 130000), -- id: 554
(150, 16, 140000, 20, 2, 224000), -- id: 555
(150, 14, 125000, 5, 3, 356250), -- id: 556
(150, 9, 130000, 10, 1, 117000), -- id: 557
(150, 45, 150000, 5, 2, 285000), -- id: 558
(151, 7, 120000, 5, 3, 342000), -- id: 559
(151, 25, 135000, 15, 2, 229500), -- id: 560
(151, 8, 140000, 10, 1, 126000), -- id: 561
(151, 33, 130000, 0, 2, 260000), -- id: 562
(152, 10, 150000, 5, 1, 142500), -- id: 563
(152, 35, 120000, 10, 3, 324000), -- id: 564
(152, 28, 125000, 0, 2, 250000), -- id: 565
(152, 44, 130000, 20, 1, 104000), -- id: 566
(153, 12, 135000, 5, 2, 257250), -- id: 567
(153, 45, 120000, 10, 1, 108000), -- id: 568
(153, 33, 130000, 15, 3, 331500), -- id: 569
(153, 7, 140000, 0, 2, 280000), -- id: 570
(154, 16, 120000, 5, 3, 342000), -- id: 571
(154, 41, 130000, 10, 2, 234000), -- id: 572
(154, 39, 135000, 20, 1, 108000), -- id: 573
(154, 22, 140000, 5, 3, 399000), -- id: 574
(155, 25, 120000, 0, 2, 240000), -- id: 575
(155, 44, 130000, 10, 1, 117000), -- id: 576
(155, 10, 135000, 5, 3, 386250), -- id: 577
(155, 31, 140000, 20, 2, 224000), -- id: 578
(156, 41, 120000, 5, 2, 228000), -- id: 579
(156, 13, 125000, 0, 3, 375000), -- id: 580
(156, 39, 135000, 10, 1, 121500), -- id: 581
(156, 53, 150000, 20, 2, 240000), -- id: 582
(157, 44, 140000, 5, 3, 399000), -- id: 583
(157, 6, 130000, 15, 2, 221000), -- id: 584
(157, 5, 120000, 0, 1, 120000), -- id: 585
(157, 12, 135000, 10, 3, 364500), -- id: 586
(158, 30, 140000, 5, 2, 266000), -- id: 587
(158, 41, 130000, 0, 1, 130000), -- id: 588
(158, 25, 150000, 20, 3, 360000), -- id: 589
(158, 17, 120000, 10, 2, 216000), -- id: 590
(159, 31, 135000, 5, 3, 396750), -- id: 591
(159, 44, 130000, 0, 1, 130000), -- id: 592
(159, 10, 120000, 15, 2, 204000), -- id: 593
(159, 13, 150000, 10, 1, 135000), -- id: 594
(160, 37, 140000, 0, 2, 280000), -- id: 595
(160, 22, 130000, 5, 3, 369750), -- id: 596
(160, 41, 120000, 10, 1, 108000), -- id: 597
(160, 33, 135000, 20, 2, 216000), -- id: 598
(161, 8, 125000, 15, 2, 212500), -- id: 599
(161, 30, 130000, 5, 1, 123500), -- id: 600
(162, 17, 135000, 10, 2, 243000), -- id: 601
(162, 40, 150000, 5, 1, 142500), -- id: 602
(162, 29, 120000, 0, 3, 360000), -- id: 603
(162, 33, 130000, 20, 2, 208000), -- id: 604
(163, 21, 140000, 5, 3, 399000), -- id: 605
(163, 15, 125000, 10, 2, 225000), -- id: 606
(163, 44, 130000, 0, 1, 130000), -- id: 607
(163, 53, 135000, 15, 1, 114750), -- id: 608
(164, 8, 150000, 5, 3, 427500), -- id: 609
(164, 37, 120000, 20, 1, 96000), -- id: 610
(164, 21, 140000, 10, 2, 252000), -- id: 611
(164, 43, 130000, 0, 3, 390000), -- id: 612
(165, 34, 120000, 5, 2, 228000), -- id: 613
(165, 27, 135000, 15, 1, 114750), -- id: 614
(165, 32, 125000, 0, 2, 250000), -- id: 615
(165, 26, 140000, 10, 3, 378000), -- id: 616
(166, 24, 130000, 5, 1, 123500), -- id: 617
(166, 42, 150000, 0, 2, 300000), -- id: 618
(166, 9, 120000, 20, 3, 288000), -- id: 619
(166, 31, 135000, 15, 2, 229500), -- id: 620
(167, 33, 140000, 0, 1, 140000), -- id: 621
(167, 13, 130000, 5, 3, 369750), -- id: 622
(167, 45, 120000, 20, 2, 192000), -- id: 623
(167, 44, 125000, 10, 2, 225000), -- id: 624
(168, 41, 150000, 5, 3, 427500), -- id: 625
(168, 29, 135000, 10, 1, 121500), -- id: 626
(168, 23, 120000, 5, 2, 228000), -- id: 627
(168, 18, 130000, 0, 1, 130000), -- id: 628
(169, 12, 140000, 5, 2, 266000), -- id: 629
(169, 27, 125000, 20, 1, 100000), -- id: 630
(169, 35, 130000, 10, 3, 351000), -- id: 631
(169, 7, 150000, 15, 2, 255000), -- id: 632
(170, 33, 120000, 5, 1, 114000), -- id: 633
(170, 40, 130000, 10, 3, 351000), -- id: 634
(170, 9, 140000, 0, 2, 280000), -- id: 635
(170, 28, 135000, 20, 1, 108000), -- id: 636
(171, 26, 150000, 5, 3, 427500), -- id: 637
(171, 7, 120000, 15, 2, 204000), -- id: 638
(171, 19, 130000, 0, 3, 390000), -- id: 639
(171, 44, 140000, 5, 1, 133000), -- id: 640
(172, 30, 125000, 10, 2, 225000), -- id: 641
(172, 23, 135000, 5, 1, 128250), -- id: 642
(172, 37, 150000, 0, 3, 450000), -- id: 643
(172, 12, 130000, 20, 2, 208000), -- id: 644
(173, 41, 120000, 15, 1, 102000), -- id: 645
(173, 42, 135000, 0, 2, 270000), -- id: 646
(173, 5, 125000, 10, 1, 112500), -- id: 647
(173, 29, 130000, 5, 3, 369750), -- id: 648
(174, 8, 150000, 20, 2, 240000), -- id: 649
(174, 9, 120000, 5, 3, 342000), -- id: 650
(175, 25, 135000, 10, 2, 243000), -- id: 651
(175, 35, 120000, 5, 3, 342000), -- id: 652
(175, 42, 130000, 0, 2, 260000), -- id: 653
(175, 44, 140000, 10, 1, 126000), -- id: 654
(176, 11, 150000, 15, 3, 382500), -- id: 655
(176, 22, 120000, 0, 1, 120000), -- id: 656
(176, 7, 135000, 20, 3, 324000), -- id: 657
(176, 38, 130000, 5, 2, 247000), -- id: 658
(177, 17, 120000, 10, 3, 324000), -- id: 659
(177, 5, 135000, 0, 1, 135000), -- id: 660
(177, 18, 140000, 5, 2, 266000), -- id: 661
(177, 31, 125000, 20, 1, 100000), -- id: 662
(178, 39, 130000, 5, 1, 123500), -- id: 663
(178, 26, 120000, 0, 3, 360000), -- id: 664
(178, 6, 140000, 15, 2, 238000), -- id: 665
(178, 24, 135000, 10, 1, 121500), -- id: 666
(179, 9, 150000, 0, 3, 450000), -- id: 667
(179, 14, 130000, 20, 2, 208000), -- id: 668
(179, 22, 120000, 5, 3, 342000), -- id: 669
(179, 5, 125000, 10, 2, 225000), -- id: 670
(180, 17, 130000, 0, 1, 130000), -- id: 671
(180, 41, 140000, 5, 2, 266000), -- id: 672
(180, 38, 120000, 15, 3, 306000), -- id: 673
(180, 7, 125000, 10, 2, 225000), -- id: 674
(181, 13, 150000, 0, 2, 300000), -- id: 675
(181, 28, 120000, 10, 3, 324000), -- id: 676
(181, 39, 130000, 5, 1, 123500), -- id: 677
(181, 24, 135000, 15, 1, 114750), -- id: 678
(182, 41, 120000, 5, 3, 342000), -- id: 679
(182, 36, 130000, 0, 2, 260000), -- id: 680
(182, 9, 135000, 10, 3, 364500), -- id: 681
(182, 14, 140000, 20, 1, 112000), -- id: 682
(183, 5, 120000, 15, 3, 306000), -- id: 683
(183, 29, 135000, 10, 2, 243000), -- id: 684
(183, 37, 150000, 0, 3, 450000), -- id: 685
(183, 32, 130000, 5, 1, 123500), -- id: 686
(184, 30, 120000, 5, 2, 228000), -- id: 687
(184, 18, 135000, 10, 1, 121500), -- id: 688
(184, 9, 140000, 0, 3, 420000), -- id: 689
(184, 8, 130000, 20, 1, 104000), -- id: 690
(185, 12, 150000, 5, 1, 142500), -- id: 691
(185, 25, 120000, 0, 2, 240000), -- id: 692
(185, 13, 135000, 15, 3, 346500), -- id: 693
(185, 7, 130000, 10, 2, 234000), -- id: 694
(186, 42, 120000, 0, 1, 120000), -- id: 695
(186, 29, 135000, 5, 3, 385500), -- id: 696
(186, 26, 150000, 10, 1, 135000), -- id: 697
(186, 5, 140000, 20, 2, 224000), -- id: 698
(187, 24, 130000, 0, 3, 390000), -- id: 699
(187, 19, 120000, 10, 2, 216000), -- id: 700
(188, 17, 135000, 5, 1, 128250), -- id: 701
(188, 24, 140000, 0, 3, 420000), -- id: 702
(188, 5, 120000, 10, 2, 216000), -- id: 703
(188, 13, 130000, 20, 1, 104000), -- id: 704
(189, 32, 125000, 5, 1, 118750), -- id: 705
(189, 19, 135000, 10, 2, 243000), -- id: 706
(189, 41, 120000, 15, 3, 306000), -- id: 707
(189, 9, 130000, 0, 2, 260000), -- id: 708
(190, 22, 150000, 5, 1, 142500), -- id: 709
(190, 17, 120000, 10, 2, 216000), -- id: 710
(190, 8, 130000, 0, 3, 390000), -- id: 711
(190, 37, 140000, 20, 1, 112000), -- id: 712
(191, 41, 135000, 5, 2, 257250), -- id: 713
(191, 7, 150000, 0, 1, 150000), -- id: 714
(191, 19, 120000, 10, 2, 216000), -- id: 715
(191, 5, 130000, 5, 3, 370500), -- id: 716
(192, 13, 140000, 15, 2, 238000), -- id: 717
(192, 26, 120000, 10, 3, 324000), -- id: 718
(192, 24, 135000, 0, 1, 135000), -- id: 719
(192, 32, 130000, 5, 2, 247000), -- id: 720
(193, 28, 150000, 10, 3, 405000), -- id: 721
(193, 9, 120000, 5, 1, 114000), -- id: 722
(193, 5, 135000, 0, 2, 270000), -- id: 723
(193, 40, 130000, 0, 3, 390000), -- id: 724
(194, 31, 125000, 5, 2, 238000), -- id: 725
(194, 9, 120000, 10, 3, 324000), -- id: 726
(194, 22, 135000, 20, 1, 108000), -- id: 727
(194, 13, 140000, 15, 2, 238000), -- id: 728
(195, 25, 120000, 0, 3, 360000), -- id: 729
(195, 32, 130000, 5, 1, 123500), -- id: 730
(195, 36, 140000, 10, 1, 126000), -- id: 731
(195, 17, 125000, 0, 2, 250000), -- id: 732
(196, 5, 150000, 10, 3, 405000), -- id: 733
(196, 8, 120000, 0, 1, 120000), -- id: 734
(196, 35, 135000, 5, 2, 257250), -- id: 735
(196, 41, 130000, 5, 3, 369000), -- id: 736
(197, 39, 120000, 15, 1, 102000), -- id: 737
(197, 18, 135000, 0, 3, 405000), -- id: 738
(197, 26, 140000, 10, 2, 252000), -- id: 739
(197, 42, 130000, 5, 3, 369000), -- id: 740
(198, 41, 125000, 0, 2, 250000), -- id: 741
(198, 9, 120000, 20, 3, 288000), -- id: 742
(198, 33, 135000, 5, 2, 257250), -- id: 743
(198, 27, 130000, 10, 3, 351000), -- id: 744
(199, 23, 140000, 15, 1, 119000), -- id: 745
(199, 24, 120000, 5, 3, 342000), -- id: 746
(199, 9, 130000, 0, 2, 260000), -- id: 747
(199, 19, 135000, 10, 2, 243000), -- id: 748
(200, 15, 120000, 5, 1, 114000), -- id: 749
(200, 17, 130000, 10, 3, 351000), -- id: 750
(201, 5, 120000, 5, 2, 228000), -- id: 751
(201, 8, 130000, 0, 1, 130000), -- id: 752
(201, 12, 140000, 10, 3, 378000), -- id: 753
(201, 41, 135000, 5, 2, 257250), -- id: 754
(202, 32, 125000, 0, 1, 125000), -- id: 755
(202, 22, 130000, 5, 3, 369000), -- id: 756
(202, 37, 140000, 10, 2, 252000), -- id: 757
(202, 16, 120000, 15, 3, 306000), -- id: 758
(203, 41, 125000, 5, 3, 393750), -- id: 759
(203, 36, 130000, 0, 2, 260000), -- id: 760
(203, 9, 120000, 10, 1, 108000), -- id: 761
(203, 13, 135000, 5, 1, 128250), -- id: 762
(204, 14, 140000, 20, 3, 336000), -- id: 763
(204, 16, 120000, 5, 2, 228000), -- id: 764
(204, 37, 130000, 0, 1, 130000), -- id: 765
(204, 41, 135000, 10, 2, 243000), -- id: 766
(205, 19, 120000, 5, 3, 342000), -- id: 767
(205, 25, 130000, 0, 1, 130000), -- id: 768
(205, 41, 140000, 15, 2, 238000), -- id: 769
(205, 9, 135000, 10, 3, 364500), -- id: 770
(206, 8, 120000, 5, 2, 228000), -- id: 771
(206, 16, 130000, 0, 3, 390000), -- id: 772
(206, 13, 135000, 10, 2, 243000), -- id: 773
(206, 5, 140000, 0, 1, 140000), -- id: 774
(207, 41, 120000, 15, 1, 102000), -- id: 775
(207, 32, 130000, 10, 2, 234000), -- id: 776
(207, 33, 140000, 5, 3, 399000), -- id: 777
(207, 24, 120000, 0, 3, 360000), -- id: 778
(208, 28, 135000, 5, 1, 128250), -- id: 779
(208, 9, 140000, 0, 2, 280000), -- id: 780
(208, 37, 120000, 10, 2, 216000), -- id: 781
(208, 13, 130000, 0, 3, 390000), -- id: 782
(209, 14, 135000, 15, 3, 343125), -- id: 783
(209, 17, 120000, 0, 1, 120000), -- id: 784
(209, 5, 130000, 10, 3, 351000), -- id: 785
(209, 19, 140000, 5, 2, 266000), -- id: 786
(210, 32, 125000, 10, 2, 225000), -- id: 787
(210, 41, 135000, 20, 3, 324000), -- id: 788
(210, 16, 130000, 0, 2, 260000), -- id: 789
(210, 24, 120000, 5, 3, 342000), -- id: 790
(211, 13, 120000, 10, 3, 324000), -- id: 791
(211, 17, 140000, 5, 2, 266000), -- id: 792
(211, 41, 135000, 0, 2, 270000), -- id: 793
(211, 9, 130000, 15, 1, 110500), -- id: 794
(212, 19, 120000, 10, 2, 216000), -- id: 795
(212, 13, 135000, 5, 3, 385500), -- id: 796
(212, 24, 130000, 0, 1, 130000), -- id: 797
(212, 32, 140000, 15, 3, 357000), -- id: 798
(213, 28, 120000, 5, 2, 228000), -- id: 799
(213, 25, 130000, 10, 1, 117000), -- id: 800
(214, 9, 140000, 5, 2, 266000), -- id: 801
(214, 32, 130000, 10, 1, 117000), -- id: 802
(214, 41, 125000, 0, 3, 375000), -- id: 803
(214, 13, 135000, 5, 1, 128250), -- id: 804
(215, 37, 120000, 20, 2, 192000), -- id: 805
(215, 16, 130000, 0, 3, 390000), -- id: 806
(215, 19, 140000, 10, 1, 126000), -- id: 807
(215, 5, 125000, 5, 2, 237500), -- id: 808
(216, 33, 130000, 10, 2, 234000), -- id: 809
(216, 17, 140000, 0, 1, 140000), -- id: 810
(216, 24, 120000, 15, 3, 306000), -- id: 811
(216, 19, 135000, 5, 2, 257250), -- id: 812
(217, 41, 130000, 10, 3, 351000), -- id: 813
(217, 5, 120000, 20, 1, 96000), -- id: 814
(217, 9, 140000, 0, 3, 420000), -- id: 815
(217, 16, 135000, 5, 2, 257250), -- id: 816
(218, 28, 120000, 15, 3, 306000), -- id: 817
(218, 32, 130000, 10, 2, 234000), -- id: 818
(218, 5, 140000, 0, 1, 140000), -- id: 819
(218, 37, 125000, 0, 2, 250000), -- id: 820
(219, 41, 135000, 5, 3, 382500), -- id: 821
(219, 19, 120000, 10, 2, 216000), -- id: 822
(219, 25, 130000, 0, 1, 130000), -- id: 823
(219, 24, 140000, 15, 3, 357000), -- id: 824
(220, 41, 130000, 5, 1, 123500), -- id: 825
(220, 5, 120000, 0, 2, 240000), -- id: 826
(220, 9, 135000, 10, 3, 364500), -- id: 827
(220, 19, 140000, 5, 2, 266000), -- id: 828
(221, 28, 125000, 0, 3, 375000), -- id: 829
(221, 41, 135000, 20, 1, 108000), -- id: 830
(221, 17, 130000, 5, 3, 369750), -- id: 831
(221, 5, 140000, 0, 2, 280000), -- id: 832
(222, 41, 125000, 15, 3, 318750), -- id: 833
(222, 9, 130000, 0, 1, 130000), -- id: 834
(222, 24, 140000, 5, 2, 266000), -- id: 835
(222, 37, 120000, 10, 3, 324000), -- id: 836
(223, 19, 130000, 5, 2, 247000), -- id: 837
(223, 32, 140000, 20, 1, 112000), -- id: 838
(223, 5, 135000, 0, 3, 405000), -- id: 839
(223, 9, 120000, 5, 1, 114000), -- id: 840
(224, 13, 130000, 0, 2, 260000), -- id: 841
(224, 41, 140000, 5, 3, 399000), -- id: 842
(224, 32, 120000, 10, 2, 216000), -- id: 843
(224, 9, 135000, 0, 1, 135000), -- id: 844
(225, 28, 120000, 15, 2, 204000), -- id: 845
(225, 41, 130000, 10, 3, 351000), -- id: 846
(225, 24, 140000, 5, 1, 133000), -- id: 847
(225, 16, 125000, 0, 2, 250000), -- id: 848
(226, 9, 135000, 10, 1, 121500), -- id: 849
(226, 19, 140000, 0, 2, 280000), -- id: 850
(227, 41, 120000, 5, 3, 342000), -- id: 851
(227, 28, 130000, 10, 2, 234000), -- id: 852
(227, 5, 140000, 0, 1, 140000), -- id: 853
(227, 9, 125000, 15, 3, 318750), -- id: 854
(228, 16, 130000, 5, 2, 247000), -- id: 855
(228, 41, 140000, 10, 1, 126000), -- id: 856
(228, 24, 120000, 0, 3, 360000), -- id: 857
(228, 37, 135000, 0, 2, 270000), -- id: 858
(229, 19, 120000, 15, 1, 102000), -- id: 859
(229, 9, 140000, 0, 3, 420000), -- id: 860
(229, 32, 130000, 5, 2, 247000), -- id: 861
(229, 5, 125000, 20, 1, 100000), -- id: 862
(230, 28, 120000, 10, 3, 324000), -- id: 863
(230, 16, 130000, 5, 1, 123500), -- id: 864
(230, 41, 140000, 0, 2, 280000), -- id: 865
(230, 9, 135000, 10, 3, 364500), -- id: 866
(231, 5, 120000, 0, 2, 240000), -- id: 867
(231, 41, 130000, 5, 1, 123500), -- id: 868
(231, 24, 140000, 20, 3, 336000), -- id: 869
(231, 28, 125000, 10, 2, 225000), -- id: 870
(232, 41, 135000, 5, 3, 382500), -- id: 871
(232, 19, 120000, 10, 2, 216000), -- id: 872
(232, 5, 130000, 0, 1, 130000), -- id: 873
(232, 9, 140000, 5, 3, 399000), -- id: 874
(233, 16, 125000, 0, 1, 125000), -- id: 875
(233, 32, 135000, 5, 2, 257250), -- id: 876
(233, 41, 140000, 20, 3, 336000), -- id: 877
(233, 28, 120000, 10, 2, 216000), -- id: 878
(234, 9, 130000, 0, 1, 130000), -- id: 879
(234, 19, 140000, 5, 3, 399000), -- id: 880
(234, 5, 125000, 10, 2, 225000), -- id: 881
(234, 41, 135000, 15, 3, 346500), -- id: 882
(235, 32, 120000, 0, 3, 360000), -- id: 883
(235, 9, 130000, 10, 1, 117000), -- id: 884
(235, 41, 140000, 5, 2, 266000), -- id: 885
(235, 19, 125000, 0, 1, 125000), -- id: 886
(236, 28, 130000, 5, 3, 369750), -- id: 887
(236, 9, 140000, 10, 2, 252000), -- id: 888
(236, 41, 120000, 0, 1, 120000), -- id: 889
(236, 5, 125000, 20, 3, 300000), -- id: 890
(237, 16, 135000, 5, 2, 257250), -- id: 891
(237, 41, 140000, 0, 3, 420000), -- id: 892
(237, 32, 130000, 10, 1, 117000), -- id: 893
(237, 24, 120000, 15, 3, 306000), -- id: 894
(238, 28, 120000, 10, 1, 108000), -- id: 895
(238, 41, 130000, 0, 3, 390000), -- id: 896
(238, 5, 140000, 5, 2, 266000), -- id: 897
(238, 9, 125000, 0, 1, 125000), -- id: 898
(239, 16, 135000, 10, 3, 364500), -- id: 899
(239, 41, 120000, 5, 2, 228000), -- id: 900
(240, 32, 130000, 0, 3, 390000), -- id: 901
(240, 5, 140000, 5, 2, 266000), -- id: 902
(240, 41, 120000, 10, 1, 108000), -- id: 903
(240, 9, 125000, 15, 3, 318750), -- id: 904
(241, 16, 130000, 0, 1, 130000), -- id: 905
(241, 32, 140000, 5, 2, 266000), -- id: 906
(241, 5, 120000, 10, 3, 324000), -- id: 907
(241, 28, 125000, 5, 1, 118750), -- id: 908
(242, 41, 135000, 20, 2, 216000), -- id: 909
(242, 9, 130000, 0, 3, 390000), -- id: 910
(242, 32, 120000, 10, 2, 216000), -- id: 911
(242, 16, 125000, 5, 1, 118750), -- id: 912
(243, 28, 140000, 5, 2, 266000), -- id: 913
(243, 41, 130000, 0, 3, 390000), -- id: 914
(243, 9, 120000, 10, 1, 108000), -- id: 915
(243, 32, 125000, 15, 2, 212500), -- id: 916
(244, 5, 130000, 0, 3, 390000), -- id: 917
(244, 9, 135000, 5, 2, 257250), -- id: 918
(244, 41, 140000, 20, 3, 336000), -- id: 919
(244, 28, 120000, 10, 1, 108000), -- id: 920
(245, 32, 125000, 0, 2, 250000), -- id: 921
(245, 9, 130000, 5, 3, 371250), -- id: 922
(245, 41, 140000, 0, 1, 140000), -- id: 923
(245, 5, 120000, 10, 2, 216000), -- id: 924
(246, 28, 135000, 5, 2, 257250), -- id: 925
(246, 41, 130000, 15, 3, 331500), -- id: 926
(246, 32, 120000, 0, 1, 120000), -- id: 927
(246, 9, 140000, 5, 2, 266000), -- id: 928
(247, 5, 130000, 10, 3, 351000), -- id: 929
(247, 41, 120000, 0, 1, 120000), -- id: 930
(247, 28, 135000, 0, 2, 270000), -- id: 931
(247, 32, 125000, 5, 3, 356250), -- id: 932
(248, 9, 130000, 10, 1, 117000), -- id: 933
(248, 28, 140000, 5, 2, 266000), -- id: 934
(248, 41, 120000, 5, 3, 342000), -- id: 935
(248, 5, 135000, 0, 1, 135000), -- id: 936
(249, 32, 130000, 5, 1, 123500), -- id: 937
(249, 9, 140000, 0, 2, 280000), -- id: 938
(249, 41, 120000, 10, 3, 324000), -- id: 939
(249, 5, 125000, 5, 2, 237500); -- id: 940