// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: order_service.proto

package orderservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllInvoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllInvoicesRequest) Reset() {
	*x = GetAllInvoicesRequest{}
	mi := &file_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvoicesRequest) ProtoMessage() {}

func (x *GetAllInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInvoicesRequest.ProtoReflect.Descriptor instead.
func (*GetAllInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{0}
}

type GetAllInvoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invoices      []*Invoice             `protobuf:"bytes,1,rep,name=invoices,proto3" json:"invoices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllInvoicesResponse) Reset() {
	*x = GetAllInvoicesResponse{}
	mi := &file_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInvoicesResponse) ProtoMessage() {}

func (x *GetAllInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInvoicesResponse.ProtoReflect.Descriptor instead.
func (*GetAllInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllInvoicesResponse) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Invoice) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Invoice) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Invoice) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Invoice) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_order_service_proto protoreflect.FileDescriptor

const file_order_service_proto_rawDesc = "" +
	"\n" +
	"\x13order_service.proto\x12\forderservice\x1a\x1fgoogle/protobuf/timestamp.proto\"\x17\n" +
	"\x15GetAllInvoicesRequest\"K\n" +
	"\x16GetAllInvoicesResponse\x121\n" +
	"\binvoices\x18\x01 \x03(\v2\x15.orderservice.InvoiceR\binvoices\"\xe3\x01\n" +
	"\aInvoice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x03R\vtotalAmount\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2o\n" +
	"\x10OrderServiceGRPC\x12[\n" +
	"\x0eGetAllInvoices\x12#.orderservice.GetAllInvoicesRequest\x1a$.orderservice.GetAllInvoicesResponseB\x11Z\x0forderservicepb/b\x06proto3"

var (
	file_order_service_proto_rawDescOnce sync.Once
	file_order_service_proto_rawDescData []byte
)

func file_order_service_proto_rawDescGZIP() []byte {
	file_order_service_proto_rawDescOnce.Do(func() {
		file_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_service_proto_rawDesc), len(file_order_service_proto_rawDesc)))
	})
	return file_order_service_proto_rawDescData
}

var file_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_order_service_proto_goTypes = []any{
	(*GetAllInvoicesRequest)(nil),  // 0: orderservice.GetAllInvoicesRequest
	(*GetAllInvoicesResponse)(nil), // 1: orderservice.GetAllInvoicesResponse
	(*Invoice)(nil),                // 2: orderservice.Invoice
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_order_service_proto_depIdxs = []int32{
	2, // 0: orderservice.GetAllInvoicesResponse.invoices:type_name -> orderservice.Invoice
	3, // 1: orderservice.Invoice.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: orderservice.Invoice.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: orderservice.OrderServiceGRPC.GetAllInvoices:input_type -> orderservice.GetAllInvoicesRequest
	1, // 4: orderservice.OrderServiceGRPC.GetAllInvoices:output_type -> orderservice.GetAllInvoicesResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_order_service_proto_init() }
func file_order_service_proto_init() {
	if File_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_service_proto_rawDesc), len(file_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_service_proto_goTypes,
		DependencyIndexes: file_order_service_proto_depIdxs,
		MessageInfos:      file_order_service_proto_msgTypes,
	}.Build()
	File_order_service_proto = out.File
	file_order_service_proto_goTypes = nil
	file_order_service_proto_depIdxs = nil
}
